### ISSUE TITLE
Incorrect syntax highlighting of cshtml files in GitHub

### ISSUE THREAD

**Issue by infinnie** [github/linguist#3760] opened 2017-08-08 03:25 UTC
Razor pages (i.e. those with an extension of `.cshtml`) are syntax highlighted using the C# syntax highlighter. However, the vast majority of a Razor page is HTML instead of C#, and the syntax highlighting of the HTML part is either absent or completely wrong. Not only that, but many of the at-directives are not correctly syntax highlighted.

(see https://github.com/infinnie/TodoServer/blob/master/TodoServer/Views/Todos/Index.cshtml )

**Comment by Alhadis** [comment] 2017-08-08 03:31
The `cshtml` extension is [currently associated](https://github.com/github/linguist/blob/f75c570/lib/linguist/languages.yml#L476) with the C# language itself, whereas it sounds like this should be categorised as a separate language altogether.

Are all `cshtml` files "Razor pages"? Or do some "ordinary" C# files use that file extension as well?

**Comment by infinnie** [comment] 2017-08-08 03:34
No ordinary C# files use that file extension.
Razor pages with the extension .cshtml are pages such as views in ASP.NET MVC or standalone ASP.NET Web Pages.

**Comment by Rabadash8820** [comment] 2017-10-23 19:07
I second this.  [Razor](https://docs.microsoft.com/en-us/aspnet/core/mvc/views/razor), like other view engines, uses a syntax that's kind of a hybrid of HTML and an actual programming language--in this case, C#.  So neither HTML nor C# is an appropriate language tag for Razor code in Github comments, issues, etc.

**Comment by worldbeater** [comment] 2018-02-09 18:08
[Visual Studio Code](https://github.com/Microsoft/vscode) editor already has [grammars that are needed to correctly highlight cshtml files](https://github.com/Microsoft/vscode/blob/master/extensions/razor/syntaxes/cshtml.tmLanguage.json). The grammars are located in Visual Studio Code syntaxes folder and are fully compatible with Atom & Github parsing engines as far as I know. So why not to take production-ready highlighters from there? [atom/language-csharp](https://github.com/atom/language-csharp) repository already uses Microsoft's grammar (but packages don't seem to be uploaded yet), so this can be done with cshtml too. @Alhadis hope this helps!

**Comment by olegburov** [comment] 2018-05-06 23:58
The `*.cshtml` is a mix of `html` and `c#`. I would say treat it as HTML, but when you see `@<expression>`, then it's a C# code.

For example:

```html
@if (User.Identity.IsAuthenticated)
{
  <ul class="nav navbar-nav navbar-right">
    <li><a asp-controller="Account" asp-action="Signout">Sign out</a></li>
  </ul>
}
else
{
  <ul class="nav navbar-nav navbar-right">
    <li><a asp-controller="Account" asp-action="Signin">Sign in</a></li>
  </ul>
}
```

Where `@<expression>` can be inside HTML tag. For instance,

```html
<img width="20" height="20" class="avatar" alt="@User.Identity.Name" src="@User.Claims.FirstOrDefault(c => c.Type == "picture")?.Value">

```

**Comment by DanVicarel** [comment] 2018-11-06 20:30
This issue is still relevant as the linguist [languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) file still considers the `.cshtml` extension to be C#.  Looks like @worldbeater provided a pretty good reference above for how this Razor highlighting can be correctly implemented.

**Comment by worldbeater** [comment] 2018-11-06 20:57
Worth using `.cshtml` grammar located at https://github.com/austincummings/razor-plus repository (see `syntaxes` directory). [See it in action](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Faustincummings%2Frazor-plus%2Fmaster%2Fsyntaxes%2Fcshtml.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Faspnet%2FMusicStore%2Fblob%2Fmaster%2Fsamples%2FMusicStore%2FViews%2FStore%2FBrowse.cshtml&code=), looks pretty good.

**Comment by pchaigno** [comment] 2018-11-06 21:37
Does one of you want to open a pull request to implement this change (move `.cshtml` to its own language entry with the adequate grammar)?

**Comment by lildude** [comment] 2018-11-20 09:45
Closing as this is resolved by https://github.com/github/linguist/pull/4314.

**Closed by lildude** 2018-11-20 09:45 UTC

**Comment by dazbradbury** [comment] 2019-01-10 11:36
Looks like there are still some issues that have resulted following this, example here:

https://gist.github.com/dazbradbury/2526da9ee866628ee10a0f2a4829253d

Previously, the red error highlighting wouldn't appear.

**Comment by lildude** [comment] 2019-01-10 11:58
@dazbradbury That's going to be a problem with the grammar itself and easily reproducible by checking it directly within [Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Faustincummings%2Frazor-plus%2Fmaster%2Fsyntaxes%2Fcshtml.tmLanguage.json&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Fdazbradbury%2F2526da9ee866628ee10a0f2a4829253d%2Fraw%2F0878a8b8aa5f095ee8a1ffb5290554bc8e52d73a%2Fcshtml_syntax_highlighting_issue.cshtml&code=).

You'll need to raise an issue against the grammar itself for this to be resolved. Once the grammar has resolved the issue, the change will automatically be pulled in in the next release of Linguist after it's fixed in the grammar.

**Comment by worldbeater** [comment] 2019-01-10 12:05
@dazbradbury the grammar used for `.cshtml` files is located [here](https://github.com/austincummings/razor-plus), just in case you wish to submit a fix.

**Comment by taori** [comment] 2019-09-07 16:36
if this was fixed at some point - cshtml is now being considered as html again - and i agree with others, that it should de it's own categorized language because it isn't actually either of those languages

**Comment by alphonso77** [comment] 2019-10-23 13:46
This is still annoying. Quotes aren't correctly being highlighted. 

![image](https://user-images.githubusercontent.com/762224/67399245-ec8ca900-f579-11e9-8516-b15430369797.png)

**Comment by lildude** [comment] 2019-10-23 14:02
> This is still annoying. Quotes aren't correctly being highlighted.

@alphonso77 This isn't a Linguist issue. This is an issue with the [grammar](https://github.com/austincummings/razor-plus). If you wish to have it resolved, you need to log an issue with the grammar.

**Comment by alphonso77** [comment] 2019-10-23 15:43
@lildude, I'm sorry - I saw the comment earlier stating that, it was just a moment of frustration.
