### ISSUE TITLE
C# project incorrectly labelled as SmallTalk

### ISSUE THREAD

**Issue by brtubb** [github/linguist#1997] opened 2015-01-15 18:42 UTC
Looks like our repo is labelled as SmallTalk while it is C#!
https://github.com/Parature -> see the ParatureSDK libary
![image](https://cloud.githubusercontent.com/assets/10502971/5763909/46423878-9cbc-11e4-9bf5-52d1451f32dc.png)

Any help appreciated!

**Comment by arfon** [comment] 2015-01-15 22:47
Duplicate of https://github.com/github/linguist/issues/1907

**Closed by arfon** 2015-01-15 22:47 UTC
