### ISSUE TITLE
Kotlin syntax highlighting stopped working in 7.12.0

### ISSUE THREAD

**Issue by nishtahir** [github/linguist#5085] opened 2020-11-06 23:56 UTC
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Kotlin highlighting seems to be broken in the latest linguist deployment, we're tracking the issue in the kotlin repo here https://github.com/nishtahir/language-kotlin/issues/33. Testing with lightshow, the latest version of the grammar seems to be working when I link to the grammar directly. However selecting the scope from the drop-down doesn't work.

### URL of the affected repository:

https://github.com/nishtahir/language-kotlin/

### Last modified on:
2020-10-18

### Expected language:
Kotlin

### Detected language:
Kotlin

**Comment by nishtahir** [comment] 2020-11-06 23:56
cc @lildude

**Comment by lildude** [comment] 2020-11-07 11:27
Ooof. 🤦  I completely missed this. Sorry.

Looks like the structure of the Kotlin grammar has changed and resulted in our grammar compiler picking the individual files in `src` and not the complete grammar in `dist` and is thus creating an incomplete [grammar file](https://gist.github.com/lildude/3737a70dc3badecf73efac6b1ccf7e2f):

```
- [ ] repository `vendor/grammars/language-kotlin` (from https://github.com/nishtahir/language-kotlin) (11 errors)
    - [ ] Grammar conversion failed. File `src/ident.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/ident.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/keywords.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/keywords.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/literals.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/literals.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/objects.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/objects.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/annotations.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/annotations.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/functions.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/functions.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/package.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/package.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/types.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/types.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/classes.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/classes.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/comments.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/comments.YAML-tmLanguage` has no scope name
    - [ ] Grammar conversion failed. File `src/imports.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/imports.YAML-tmLanguage` has no scope name
```

I think this is easy enough to change in the compiler. I'll take a look at this on Monday.

**Comment by l1ving** [comment] 2020-11-07 23:08
Confirmed on both mobile website, mobile app and desktop website

**Comment by nishtahir** [comment] 2020-11-07 23:25
> Ooof. 🤦 I completely missed this. Sorry.
> 
> Looks like the structure of the Kotlin grammar has changed and resulted in our grammar compiler picking the individual files in `src` and not the complete grammar in `dist` and is thus creating an incomplete [grammar file](https://gist.github.com/lildude/3737a70dc3badecf73efac6b1ccf7e2f):
> 
> ```
> - [ ] repository `vendor/grammars/language-kotlin` (from https://github.com/nishtahir/language-kotlin) (11 errors)
>     - [ ] Grammar conversion failed. File `src/ident.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/ident.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/keywords.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/keywords.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/literals.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/literals.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/objects.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/objects.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/annotations.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/annotations.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/functions.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/functions.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/package.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/package.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/types.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/types.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/classes.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/classes.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/comments.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/comments.YAML-tmLanguage` has no scope name
>     - [ ] Grammar conversion failed. File `src/imports.YAML-tmLanguage` failed to parse: Undeclared scope in grammar: `src/imports.YAML-tmLanguage` has no scope name
> ```
> 
> I think this is easy enough to change in the compiler. I'll take a look at this on Monday.

My repo has a JSON grammar distribution. Would it be possible to point to that temporarily before the compiler fix?
It would be unfortunate to not have any syntax highlighting before a change to the compiler can be made/tested/deployed.

**Comment by lildude** [comment] 2020-11-08 10:17
> Would it be possible to point to that temporarily before the compiler fix?

Unfortunately not as I couldn't deploy the grammar update to GitHub.com until Monday due as the PR would need approval before it can be deployed. I'm based on the UK so will have everything in place for when my US colleges come online.

**Comment by LouisCAD** [comment] 2020-11-09 10:33
BTW, can you please avoid deploying on Fridays going forward? 🙂 
That can help getting hotfixes before everyone notice the issue 😉

**Comment by lildude** [comment] 2020-11-09 11:43
> BTW, can you please avoid deploying on Fridays going forward? 🙂
> That can help getting hotfixes before everyone notice the issue 😉

I normally do, but I'm pushed for time to include this in the latest GitHub Enterprise Server (GHES) release so pushing Friday allowed the issue to be detected and fixed before it gets included in GHES which is much slower to update.

I'm in the process of releasing v7.12.1 which fixes this so should be fixed 🔜 .

**Comment by lildude** [comment] 2020-11-09 12:13
Re-opening as this won't be fixed until the grammars have been deployed.

**Comment by lildude** [comment] 2020-11-09 13:33
Syntax highlighting is now working again. Sorry for the inconvenience peeps. Closing.

**Closed by lildude** 2020-11-09 13:33 UTC

**Comment by sudoFerraz** [comment] 2020-11-09 13:35
@lildude Funny thing, it was working indeed after you deployed but as soon as I refreshed the page it stopped working again, will keep monitoring for any unexpected behaviour.

**Comment by l1ving** [comment] 2020-11-09 14:03
Thanks :)

**Comment by ggoudeau-chwy** [comment] 2020-11-09 15:41
@lildude Thanks for fixing! Much appreciated. One question though- is the expectation that annotations get a special highlighting? Looks like they're still not highlighted differently, but I'm not sure what the behavior was prior to this fix, so this may not be an issue.

```kotlin
@Test
fun thisIsATest() {
}
```

**Comment by l1ving** [comment] 2020-11-09 15:43
Yes. Before it would have shown all in the same font color, meaning highlighting wasn't working

**Comment by lildude** [comment] 2020-11-09 15:49
> One question though- is the expectation that annotations get a special highlighting?

I have no idea 😁 You'd need to ask the grammar maintainer over in https://github.com/nishtahir/language-kotlin/

**Comment by nishtahir** [comment] 2020-11-09 16:21
@ggoudeau-chwy That is the expected behavior. There is a scope being applied to annotations however that scope isn't given special treatment in the github theme.
