### ISSUE TITLE
Updated grammar not being applied

### ISSUE THREAD

**Issue by nwhetsell** [github/linguist#3428] opened 2017-01-12 01:55 UTC
I suspect I’m just being impatient, but I noticed that some updates to Csound grammars aren’t being applied to files. (Full disclosure: I contributed the Csound grammars to Linguist.) For example, here’s what [this file](https://github.com/rorywalsh/Morpheus/blob/master/Morpheus.csd) looks like on GitHub:

![github morpheus](https://cloud.githubusercontent.com/assets/14102861/21873830/33f5d484-d83f-11e6-8022-6e3b09ee4607.png)

And [here](https://github-lightshow.herokuapp.com/?utf8=✓&scope=from-url&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fnwhetsell%2Flanguage-csound%2Fmaster%2Fgrammars%2Fcsound-document.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Frorywalsh%2FMorpheus%2Fmaster%2FMorpheus.csd) is the same file on Lightshow, using the same grammar:

![lightshow morpheus](https://cloud.githubusercontent.com/assets/14102861/21873888/9984316a-d83f-11e6-9248-0a046c1f7239.png)

I’m looking specifically at the keyword, function, and string highlighting. (The `^M` thing is likely [unrelated](https://github.com/github/linguist/issues/3418).)

**Comment by pchaigno** [comment] 2017-01-12 10:15
Normally, we retrieve any grammar update automatically with each new release. 
When were the changes to the grammar committed?

**Comment by nwhetsell** [comment] 2017-01-12 11:50
The changes were committed on [Jan 8](https://github.com/nwhetsell/language-csound/commit/1e68cb55d7666feccb62ca523d21e26c3fd09bbb). The changes also appear in commit https://github.com/github/linguist/commit/50c08bf29e6e4de3623d5e7177c5e05ed1200348#diff-5, before the v5.0.1 release.

**Comment by pchaigno** [comment] 2017-01-12 11:55
Hm, that *should* work, I can't see any issue on Linguist's side.
@brandonblack Any idea?

**Comment by brandonblack** [comment] 2017-01-13 22:23
Sooo... the issue is that GitHub hasn't upgraded to v5.0.x just yet. 😬 I'm actively working on this, but the we ran into some internal blockers on the upgrade that we're working through. 🔜

**Comment by jtbandes** [comment] 2017-01-20 07:57
FWIW, I noticed the same with the Swift grammar. Just look at this eyesore! (which I've hopefully fixed for whenever the release goes out 😉)

```swift
42 + 0xFF
```

**Comment by brandonblack** [comment] 2017-01-24 19:42
This should be resolved now, keyword highlighting looks correct.

**Closed by brandonblack** 2017-01-24 19:42 UTC

**Comment by jtbandes** [comment] 2017-01-24 20:18
Great, thanks!
