### ISSUE TITLE
Userscript syntax support

### ISSUE THREAD

**Issue by Bluscream** [github/linguist#4618] opened 2019-08-23 00:13 UTC
## Preliminary Steps

Please confirm you have...
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),

## Problem Description

I would like to have userscript syntax highlighting on github. i know there is general JS highlighting but its not good in the META block. I think the syntax is called ECMA or smth?
```
If you implement it please implement it to work with
```ecma
```userscript
```coffeescript
```

### Expected language:
`.user.js`

### Detected language:
`.js`

**Comment by Alhadis** [comment] 2019-08-23 00:22
> - [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
> - [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,

So, did you read those links?

**Comment by Bluscream** [comment] 2019-08-23 00:34
> > * [x]  reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
> > * [x]  reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
> 
> So, did you read those links?

Yes, i have read `If Linguist doesn't know about the language or the extension you're using, consider contributing to Linguist by opening a pull request to add support for your language or extension.`.
But as i don't have any experience in ruby, i'll have to stick to a Issue and hope it either gets implemented officially or by some other 3rd party.

**Comment by lildude** [comment] 2019-08-23 08:25
>  I think the syntax is called ECMA or smth?

I'm pretty sure it's good ol' Javascript and should and _does_ highlight fine with the Javascript grammar as can be seen at a random example I found at https://github.com/StylishThemes/GitHub-Dark-Script/blob/master/github-dark-script.user.js

Knocking up a completely useless fabrication and marking it as Javascript inline works too:

```javascript
// ==UserScript==
// @name        foobar
// @version     0.0.1
// ==/UserScript==
(() => {
  "use strict";
  const version = GM.info.script.version,
})
```

So unless I'm missing something, support is already there.

**Comment by Alhadis** [comment] 2019-08-23 08:41
ECMAScript *is* JavaScript. Specifically, the more formal name for the language as specified by ecma-262.

**Comment by Bluscream** [comment] 2019-08-23 12:45
> > I think the syntax is called ECMA or smth?
> 
> I'm pretty sure it's good ol' Javascript and should and _does_ highlight fine with the Javascript grammar as can be seen at a random example I found at https://github.com/StylishThemes/GitHub-Dark-Script/blob/master/github-dark-script.user.js
> 
> Knocking up a completely useless fabrication and marking it as Javascript inline works too:
> 
> 
> ```js
> // ==UserScript==
> // @name        foobar
> // @version     0.0.1
> // ==/UserScript==
> (() => {
>   "use strict";
>   const version = GM.info.script.version,
> })
> ```
> 
> So unless I'm missing something, support is already there.

Indeed, this is the part that you're missing:
![image](https://user-images.githubusercontent.com/3318223/63593635-aa181180-c5b4-11e9-8538-c2aa8c3a7e02.png)

**Comment by pchaigno** [comment] 2019-08-23 12:52
@Bluscream You'll have to explain in more details, because it's still not clear what the issue is.

**Comment by Bluscream** [comment] 2019-08-23 13:07
The META block has no SYNTAX HIGHLIGHING because it is interpreted as a JAVASCRIPT comment. Clear enough?

**Comment by pchaigno** [comment] 2019-08-23 13:16
Ah, I see (not that the uppercase helped...). You were expecting the tokens (`@name`, `0.0.1`, etc.) of the header comments to be highlighted as well.

I'm not sure you actually read [How Linguist Works](https://github.com/github/linguist#how-linguist-works), but this "issue" should be solved in the appropriate grammar, not Linguist. For JavaScript, we use [atom/language-javascript](https://github.com/atom/language-javascript). If you think `user.js` files should be highlighted differently than other `.js` files, then fill free to submit a pull request to add a new language entry using a different grammar. Please see the contribution guidelines in that case.

**Comment by Bluscream** [comment] 2019-08-23 13:27
As i stated above i am not good with ruby, etc.. thats why i made this a issue and not a PR in the first place

**Comment by pchaigno** [comment] 2019-08-23 13:44
If you read the contribution guidelines, you will see that there is no Ruby to write to do this. You might even not need to set up a Ruby dev. environment. In any case, this issue is probably best addressed in the JavaScript grammar's repository.

**Comment by Bluscream** [comment] 2019-08-23 21:07
So when this gets through it also changes how atom shows userscripts?

**Comment by lildude** [comment] 2019-08-24 06:13
> So when this gets through it also changes how atom shows userscripts?

It would really be the other way round: once the Atom grammar supports userscript, Linguist and thus GitHub.com can then support it to. 

As @pchaigno said, this is really a grammar issue, not a Linguist issue. A grammar needs to support userscript as you with before Atom, VS Code and GitHub can as they all use the grammar.

**Comment by Bluscream** [comment] 2019-08-24 11:29
Thanks, i will move the issue

**Closed** 2019-08-24 13:09 UTC
