### ISSUE TITLE
my Crystal repository is seen as 97.7% HTML

### ISSUE THREAD

**Issue by azah** [github/linguist#3658] opened 2017-05-31 19:25 UTC
https://github.com/azah/cowapi/tree/master

**Comment by azah** [comment] 2017-05-31 19:46
this test.html file I had checked in was the issue.
https://github.com/azah/cowapi/blob/c577e327707ba81cd6d4bbe102f3a14415cc0aeb/spec/test.html

**Comment by lildude** [comment] 2017-06-01 03:57
Good to see you found the cause. Closing.

**Closed by lildude** 2017-06-01 03:57 UTC

**Comment by grahamc** [comment] 2017-06-01 12:40
but the test.html file is valid HTML

**Comment by lildude** [comment] 2017-06-01 13:30
@grahamc I'm not sure I understand why you're pointing that out.

**Comment by Alhadis** [comment] 2017-06-01 13:38
I'm not particularly sure either... 😕

**Comment by grahamc** [comment] 2017-06-01 13:49
D'oh! Sorry for the noise. I was confused and thought the test was being categorized as Crystal incorrectly. Sorry again!
