### ISSUE TITLE
JMP Scripting Language (JSL)

### ISSUE THREAD

**Issue by VDFaller** [github/linguist#4691] opened 2019-10-30 15:11 UTC
I'd like to add a `jsl` extension to linguist for the jmp scripting language, but according to your guidelines:

> We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.   

And JSL isn't even recognized by github as a language and from what I can tell there are no searchable repos with `.jsl` files, let alone hundreds.  Just wondering if I should take the time to create this if it won't be merged.   

## Preliminary Steps

Please confirm you have...
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

### Last modified on:
2019-10-30

Apologies if this isn't the way to contact the maintainers about this.

**Comment by pchaigno** [comment] 2019-10-30 15:23
Hello :wave: 

If you improve [this search query](https://github.com/search?p=1&q=extension%3Ajsl+NOT+jfhdfdhfjdj&type=Code) (i.e., add keywords) to return only JSL files, we can then use it to compute the number of repositories. Based on that we'll be able to :+1: or :-1: a potential pull request. Of course, if you find less than 200 files, we don't need to compute the number of repositories to know it will be less than hundreds :-)

**Comment by sorasheedi5114** [comment] 2019-12-13 17:22
This issue has been automatically closed because it has not had activity in a long time. Please feel free to reopen it or create a new issue.

**Comment by sorasheedi5114** [comment] 2019-12-13 17:24
> I'd like to add a `jsl` extension to linguist for the jmp scripting language, but according to your guidelines:
> 
> > We try only to add languages once they have some usage on GitHub. In most cases we prefer that each new file extension be in use in hundreds of repositories before supporting them in Linguist.
> 
> And JSL isn't even recognized by github as a language and from what I can tell there are no searchable repos with `.jsl` files, let alone hundreds. Just wondering if I should take the time to create this if it won't be merged.
> 
> ## Preliminary Steps
> Please confirm you have...
> 
> * [x]  verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).
> 
> ### Last modified on:
> 2019-10-30
> 
> Apologies if this isn't the way to contact the maintainers about this.

Duplicate of #

**Closed** 2019-12-13 17:27 UTC
