### ISSUE TITLE
Fennel not detected

### ISSUE THREAD

**Issue by alexaandru** [github/linguist#5493] opened 2021-07-31 16:17 UTC
## Describe the bug
Fennel language (.fnl) is (apparently) not detected: 1) doesn't show up in languages breakdown 2) gets no syntax highlight.

### Expected behaviour
From what I've read in the README and what I see in here:
https://github.com/github/linguist/blob/a3a3b8b330d296589f103d322303826a4c2bcfda/lib/linguist/languages.yml#L1679-L1688
I would think that Fennel is supported if using the correct file extension (.fnl), which I am.

You can see a sample repo here: https://github.com/alexaandru/nvim-config which has plenty of files under `fnl/` folder, but the repo is considered "100% Vimscript", even though I have a single line of it, in `init.vim`.

Also, you can see that none of the `.fnl` files get any syntax highlighting.

**Comment by lildude** [comment] 2021-08-01 07:04
This is expected as I've not deployed the latest update to Linguist to GitHub.com. I'll be doing this on Monday. See https://github.com/github/linguist/pull/5489

Closing as this is not a bug and expected behaviour.

**Closed by lildude** 2021-08-01 07:04 UTC
Labels: Bug

**Comment by lildude** [comment] 2021-08-02 11:10
Linguist v7.16.0 has now been deployed to GitHub.com and your Fennel files are now showing syntax highlighting. You'll need to push a change to your repo to force a reanalysis to update the language breakdown in the sidebar.

**Comment by alexaandru** [comment] 2021-08-02 11:49
Wow, this is amazing! Works like a charm, thank you very much! Cheers! :)
