### ISSUE TITLE
Linguist does not ignore the specified vendor code from stats

### ISSUE THREAD

**Issue by dinhluongzalora** [github/linguist#5451] opened 2021-07-11 09:30 UTC
## Describe the bug
In my repo, with `.gitattributes` I have set this to ignore the vendor libraries/code:
```
ops/infra/terraform/lambda/* linguist-vendored
``` 

Checked the attribute set if it's set correctly:
`$ git check-attr --all ops/infra/terraform/lambda/*`
The output displays:
```
ops/infra/terraform/lambda/certifi: linguist-vendored: set
ops/infra/terraform/lambda/certifi-2019.3.9.dist-info: linguist-vendored: set
ops/infra/terraform/lambda/chardet: linguist-vendored: set
ops/infra/terraform/lambda/chardet-3.0.4.dist-info: linguist-vendored: set
ops/infra/terraform/lambda/ecs_protection_asg.py: linguist-vendored: set
ops/infra/terraform/lambda/idna: linguist-vendored: set
ops/infra/terraform/lambda/idna-2.8.dist-info: linguist-vendored: set
ops/infra/terraform/lambda/requests: linguist-vendored: set
ops/infra/terraform/lambda/requests-2.21.0.dist-info: linguist-vendored: set
ops/infra/terraform/lambda/urllib3: linguist-vendored: set
ops/infra/terraform/lambda/urllib3-1.24.1.dist-info: linguist-vendored: set
```
When running 
`$ github-linguist --breakdown`
The output in my local showed Linguist successfully recognized these libraries as Python 
```
59.94%  Python

....

Python:
ops/infra/terraform/lambda/certifi/__init__.py
ops/infra/terraform/lambda/certifi/__main__.py
ops/infra/terraform/lambda/certifi/core.py
ops/infra/terraform/lambda/chardet/__init__.py
ops/infra/terraform/lambda/chardet/big5freq.py
ops/infra/terraform/lambda/chardet/big5prober.py
ops/infra/terraform/lambda/chardet/chardistribution.py
ops/infra/terraform/lambda/chardet/charsetgroupprober.py
ops/infra/terraform/lambda/chardet/charsetprober.py
ops/infra/terraform/lambda/chardet/cli/__init__.py
ops/infra/terraform/lambda/chardet/cli/chardetect.py
ops/infra/terraform/lambda/chardet/codingstatemachine.py
ops/infra/terraform/lambda/chardet/compat.py
ops/infra/terraform/lambda/chardet/cp949prober.py
ops/infra/terraform/lambda/chardet/enums.py
ops/infra/terraform/lambda/chardet/escprober.py
ops/infra/terraform/lambda/chardet/escsm.py
ops/infra/terraform/lambda/chardet/eucjpprober.py
ops/infra/terraform/lambda/chardet/euckrfreq.py
ops/infra/terraform/lambda/chardet/euckrprober.py
ops/infra/terraform/lambda/chardet/euctwfreq.py
ops/infra/terraform/lambda/chardet/euctwprober.py
ops/infra/terraform/lambda/chardet/gb2312freq.py
ops/infra/terraform/lambda/chardet/gb2312prober.py
ops/infra/terraform/lambda/chardet/hebrewprober.py
ops/infra/terraform/lambda/chardet/jisfreq.py
ops/infra/terraform/lambda/chardet/jpcntx.py
ops/infra/terraform/lambda/chardet/langbulgarianmodel.py
ops/infra/terraform/lambda/chardet/langcyrillicmodel.py
ops/infra/terraform/lambda/chardet/langgreekmodel.py
ops/infra/terraform/lambda/chardet/langhebrewmodel.py
ops/infra/terraform/lambda/chardet/langhungarianmodel.py
ops/infra/terraform/lambda/chardet/langthaimodel.py
ops/infra/terraform/lambda/chardet/langturkishmodel.py
ops/infra/terraform/lambda/chardet/latin1prober.py
ops/infra/terraform/lambda/chardet/mbcharsetprober.py
ops/infra/terraform/lambda/chardet/mbcsgroupprober.py
ops/infra/terraform/lambda/chardet/mbcssm.py
ops/infra/terraform/lambda/chardet/sbcharsetprober.py
ops/infra/terraform/lambda/chardet/sbcsgroupprober.py
ops/infra/terraform/lambda/chardet/sjisprober.py
ops/infra/terraform/lambda/chardet/universaldetector.py
ops/infra/terraform/lambda/chardet/utf8prober.py
ops/infra/terraform/lambda/chardet/version.py
ops/infra/terraform/lambda/idna/__init__.py
ops/infra/terraform/lambda/idna/codec.py
ops/infra/terraform/lambda/idna/compat.py
ops/infra/terraform/lambda/idna/core.py
ops/infra/terraform/lambda/idna/idnadata.py
ops/infra/terraform/lambda/idna/intranges.py
ops/infra/terraform/lambda/idna/package_data.py
ops/infra/terraform/lambda/idna/uts46data.py
ops/infra/terraform/lambda/requests/__init__.py
ops/infra/terraform/lambda/requests/__version__.py
ops/infra/terraform/lambda/requests/_internal_utils.py
ops/infra/terraform/lambda/requests/adapters.py
ops/infra/terraform/lambda/requests/api.py
ops/infra/terraform/lambda/requests/auth.py
ops/infra/terraform/lambda/requests/certs.py
ops/infra/terraform/lambda/requests/compat.py
ops/infra/terraform/lambda/requests/cookies.py
ops/infra/terraform/lambda/requests/exceptions.py
ops/infra/terraform/lambda/requests/help.py
ops/infra/terraform/lambda/requests/hooks.py
ops/infra/terraform/lambda/requests/models.py
ops/infra/terraform/lambda/requests/packages.py
ops/infra/terraform/lambda/requests/sessions.py
ops/infra/terraform/lambda/requests/status_codes.py
ops/infra/terraform/lambda/requests/structures.py
ops/infra/terraform/lambda/requests/utils.py
ops/infra/terraform/lambda/urllib3/__init__.py
ops/infra/terraform/lambda/urllib3/_collections.py
ops/infra/terraform/lambda/urllib3/connection.py
ops/infra/terraform/lambda/urllib3/connectionpool.py
ops/infra/terraform/lambda/urllib3/contrib/_appengine_environ.py
ops/infra/terraform/lambda/urllib3/contrib/_securetransport/bindings.py
ops/infra/terraform/lambda/urllib3/contrib/_securetransport/low_level.py
ops/infra/terraform/lambda/urllib3/contrib/appengine.py
ops/infra/terraform/lambda/urllib3/contrib/ntlmpool.py
ops/infra/terraform/lambda/urllib3/contrib/pyopenssl.py
ops/infra/terraform/lambda/urllib3/contrib/securetransport.py
ops/infra/terraform/lambda/urllib3/contrib/socks.py
ops/infra/terraform/lambda/urllib3/exceptions.py
ops/infra/terraform/lambda/urllib3/fields.py
ops/infra/terraform/lambda/urllib3/filepost.py
ops/infra/terraform/lambda/urllib3/packages/__init__.py
ops/infra/terraform/lambda/urllib3/packages/backports/makefile.py
ops/infra/terraform/lambda/urllib3/packages/six.py
ops/infra/terraform/lambda/urllib3/packages/ssl_match_hostname/__init__.py
ops/infra/terraform/lambda/urllib3/packages/ssl_match_hostname/_implementation.py
ops/infra/terraform/lambda/urllib3/poolmanager.py
ops/infra/terraform/lambda/urllib3/request.py
ops/infra/terraform/lambda/urllib3/response.py
ops/infra/terraform/lambda/urllib3/util/__init__.py
ops/infra/terraform/lambda/urllib3/util/connection.py
ops/infra/terraform/lambda/urllib3/util/queue.py
ops/infra/terraform/lambda/urllib3/util/request.py
ops/infra/terraform/lambda/urllib3/util/response.py
ops/infra/terraform/lambda/urllib3/util/retry.py
ops/infra/terraform/lambda/urllib3/util/ssl_.py
ops/infra/terraform/lambda/urllib3/util/timeout.py
ops/infra/terraform/lambda/urllib3/util/url.py
ops/infra/terraform/lambda/urllib3/util/wait.py

```

However, when I pushed `.gitattributes` to my repo and then several changes have been made to repo, which I believe it met the requirement for the Stats to update as in https://github.com/github/linguist/blob/master/docs/overrides.md 
```
When testing with a local installation of Linguist, take note that the added attributes will not take effect until the .gitattributes file is committed to your repository.
```

### Expected behaviour

Vendored code should be excluded from stat for repo as configured in `.gitattributes`

**Comment by lildude** [comment] 2021-07-11 12:26
Here's your problem:

> ops/infra/terraform/lambda/* linguist-vendored

`*` does not recurse so you'll only be marking the files within that directory as vendored and none of the files in the sub-directories. You need to change this to `**` for recursion to apply.

See my comment at https://github.com/github/linguist/discussions/5175#discussioncomment-317382 for more details.

Moving this to discussions as this is not a bug.

**Closed** 2021-07-11 12:27 UTC
