### ISSUE TITLE
D syntax highlighting broken

### ISSUE THREAD

**Issue by CodeMyst** [github/linguist#5140] opened 2021-01-13 20:59 UTC
### URL of the affected repository:

https://github.com/CodeMyst/pastemyst/blob/main/source/pastemyst/paste/create.d#L172-L203

### Last modified on:
2020-12-03

Seems like it doesn't recognize the ++ style comments

```d
/++
 + doc comment
 +/ 

/**
 * also a doc comment
 * /
```

**Comment by lildude** [comment] 2021-01-14 09:52
🤔 I'm sorry to inform you but your haste to open this issue and ignoring the "Preliminary Steps" in the template and links within has resulted in you wasting some of your precious time.

This is clear because the second checkbox is:

> - [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,

The third point in that document tells you where you should have logged this issue... hint, it's in **bold** letters, and it's not this repo 😉

Please review the Troubleshooting documentation and open a ticket in the correct repo.

If and when the issue is resolved, it'll be pulled into Linguist and thus GitHub.com, the next time a full (not patch) release is made.

I'm closing this issue as this is the wrong location for this issue.

**Closed by lildude** 2021-01-14 09:52 UTC
