### ISSUE TITLE
So, I'm not sure when this happened exactly, but it looks like GitHub is now displaying language colours underneath code-search results as well:

### ISSUE THREAD

**Issue by MiladHassani73** [github/linguist#4969] opened 2020-08-25 23:23 UTC
So, I'm not sure when this happened exactly, but it looks like GitHub is now displaying language colours underneath code-search results as well:

<img src="https://user-images.githubusercontent.com/2346707/67149227-66abfc00-f2f4-11e9-8d2c-891d1ceeca43.png" alt="Figure 1" />

Which is going to leave a lot of grey for `data`/`prose` languages...

_Originally posted by @Alhadis in https://github.com/github/linguist/issues/4506#issuecomment-544179259_

**Comment by lildude** [comment] 2020-08-26 08:43
Whoops. I missed that originally.

This happened quite some time ago and is the case in your repo list too. This is expected behaviour. 

The reason for the grey (`#cccccc`) is that is the default colour when no colour is associated with a language in [`languages.yml`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).

As data and prose languages don't normally appear in the language bar in the sidebar, we don't enforce a colour for them. This is also an advantage as we're ([still](https://github.com/github/linguist/issues/4506#issuecomment-532768155)) limited by the colour proximity used by languages for accessibility reasons so by adding a colour to a data or prose language we're potentially taking away a colour from a programming or markup language which would show in the language bar.

**Comment by pchaigno** [comment] 2020-08-29 12:40
We'll accept addition of colors to `data` and `prose` languages. If you want to fix any of these grey colors, please send a pull request!

**Comment by Alhadis** [comment] 2020-08-29 13:09
> We'll accept additions of colours to `data` and `prose` languages.

[Since when?](https://github.com/github/linguist/blob/c362ab8b3f4f66cbfa7568cf8cb20f7a560de928/test/test_language.rb#L473-L476)

**Comment by pchaigno** [comment] 2020-08-29 13:54
Since now I guess. Given these colors are now displayed, we should allow their addition.

**Comment by Alhadis** [comment] 2020-08-29 14:10
I say we wait for the colour-proximity requirement to be nuked first.

Or better yet, we don't wait and just go ahead and crush it. It'd serve GitHub's design-team right for taking (literally) years to decide if similar-looking colours from two-facelifts ago are still a problem. 😜

**Comment by pchaigno** [comment] 2020-08-29 14:17
Yeah, I agree. It's becoming tiring to have our contributions to this "open source" project blocked by dependencies to GitHub's closed source code. We're giving a lot of our time to a project that GitHub is happy to call "community-driven" when that can reduce the workload while clearly being GitHub-driven in terms of releases & design decisions.

@lildude Please improve this status quo.

**Comment by lildude** [comment] 2020-08-30 10:29
> > We'll accept additions of colours to `data` and `prose` languages.
> 
> [Since when?](https://github.com/github/linguist/blob/c362ab8b3f4f66cbfa7568cf8cb20f7a560de928/test/test_language.rb#L473-L476)

Ooops. I missed that. 😊 

> Or better yet, we don't wait and just go ahead and crush it. It'd serve GitHub's design-team right for taking (literally) years to decide if similar-looking colours from two-facelifts ago are still a problem. 😜

I'm thiiiiiiis close to doing it and dealing with the fallout if and when it happens 😬. If I were to 🔥 it, do we want to allow duplicate colours? I'm thinking not at first as we'll end up with a million identical reds or blues.

> Yeah, I agree. It's becoming tiring to have our contributions to this "open source" project blocked by dependencies to GitHub's closed source code. We're giving a lot of our time to a project that GitHub is happy to call "community-driven" when that can reduce the workload while clearly being GitHub-driven in terms of releases & design decisions.

I hear you, and I'm in the same boat to a large extent. I'm now a team of one who (informally) maintains Linguist within GitHub and I have nothing to do with the design teams and am never mentioned when there are changes in the design around the languages. The slow release cycle of late is entirely my fault and I apologise. I won't get into the details other than to say I can't prioritise Linguist so it falls into my spare time as it does for you. I also like to wait for an accumulation of approved PRs before making a release to make the release feel more substantial.

**Comment by Alhadis** [comment] 2020-08-30 10:35
> If I were to 🔥 it, do we want to allow duplicate colours? I'm thinking not at first as we'll end up with a million identical reds or blues

Yes, of course. Otherwise, we'd end up with squabbles over which language is more deserving of `#f00`, and we'd have no argument to justify this outside of a popularity contest. If a repository has identical-looking shades of red and blue… congratulations, that's what colour-blind users are already seeing. 😉

**Comment by wopian** [comment] 2020-09-08 20:31
I think this can be closed now with https://github.com/github/linguist/pull/4980 deployed in https://github.com/github/linguist/pull/4993 👍 

![image](https://user-images.githubusercontent.com/3440094/92524615-4e99df80-f21a-11ea-92ac-5eb51bffa49b.png)

**Comment by lildude** [comment] 2020-10-07 08:42
Colours are now slowly being updated and filtering through so I'm closing this issue.

**Closed by lildude** 2020-10-07 08:42 UTC
