### ISSUE TITLE
Protocol Buffers are still detected as Pure Basic

### ISSUE THREAD

**Issue by jcwchen** [github/linguist#5243] opened 2021-03-02 17:16 UTC
Same as https://github.com/github/linguist/issues/3816.

In onnx https://github.com/onnx/onnx/issues/3307, .pb files are still detected as Pure Basic. Is it expected behavior? Thank you.

**Comment by lildude** [comment] 2021-03-02 18:21
> Is it expected behavior? Thank you.

In a way, yes, because `.pb` is still only associated with Pure Basic as no one has submitted a PR to add support for Protocol Buffers.

We have https://github.com/github/linguist/issues/5091 open for this already so I'm closing this as a duplicate of that issue. 

If you have the resources and time, feel free to submit a PR. Deets on what needs to be done can be found in the CONTRIBUTING.md file.

**Closed by lildude** 2021-03-02 18:21 UTC
Labels: Bug
