### ISSUE TITLE
Add support for Svelte

### ISSUE THREAD

**Issue by Zerotask** [github/linguist#5830] opened 2022-03-17 23:27 UTC
## Language name
Svelte (a frontend compiler, similar to React / Vue)

## URL of example repository
https://github.com/Lleweraf/supachat
https://svelte.dev/repl/hello-world

## URL of syntax highlighting grammar
https://github.com/sveltejs/svelte

## Detected language
.svelte is similar to an HTML file.
It can consist of a script, html and css part.

**Comment by lildude** [comment] 2022-03-18 07:34
Linguist already has support for Svelte:

https://github.com/github/linguist/blob/3c3b037910006fc2f1a9bb34b2c4e9cde062206c/lib/linguist/languages.yml#L6086-L6095

The repo you linked to even shows it as the most used language in that repo.

Closing as there's nothing to implement. If you are experiencing problem with classification in your repo, please open a new [discussion](https://github.com/github/linguist/discussions).

**Closed by lildude** 2022-03-18 07:34 UTC
Labels: Add Language, Good First Issue

**Comment by Zerotask** [comment] 2022-03-18 09:58
https://github.com/Lleweraf/supachat/blob/latest/src/components/ChatInput.svelte

The JS and Style part are not syntax highlighted.

**Comment by lildude** [comment] 2022-03-18 10:04
It is:

![CleanShot 2022-03-18 at 10 00 36](https://user-images.githubusercontent.com/627280/158982349-2e5329cb-d8c1-459d-99ad-bc75201365a3.png)

[...]

![CleanShot 2022-03-18 at 10 00 52](https://user-images.githubusercontent.com/627280/158982369-fea13a96-db5b-40b4-bfd8-7a73bd3f38b1.png)

I've confirmed it with https://screenshot.guru/ too.

If you're not seeing it, it's probably something specific to you and outside of Linguist's control.

**Comment by Zerotask** [comment] 2022-03-18 10:06
That's interesting. Then this is a bug in the (android) mobile app.

![Screenshot_2022-03-18-11-05-28-151_com.github.android.jpg](https://user-images.githubusercontent.com/20150243/158983183-23ea07e1-2c4c-49c2-8a57-3bcb2e7602fa.jpg)
![Screenshot_2022-03-18-11-05-38-330_com.github.android.jpg](https://user-images.githubusercontent.com/20150243/158983209-e19c049b-7aa1-4d76-a7dc-c741bc72e622.jpg)

**Comment by lildude** [comment] 2022-03-18 11:32
Yup, that's definitely outside of Linguist's control. I recommend you open a support ticket using the "Contact GitHub" link at the bottom on any page on the GitHub site.

**Comment by lildude** [comment] 2022-07-22 09:01
As before, this isn't within Linguist's control @Darkle. I've tested things further and it looks like this is a problem with the grammar and not GitHub. You'll need to raise an issue with the upsteam grammar.

**Comment by jasonlyu123** [comment] 2022-07-26 15:45
There seems to be an updated linguist to switch from a forked version of svelte-atom to the latest version of the official version. The new version is partially rewritten to inject js/CSS into svelte files.

And currently, it seems like the injected part doesn't work. Specifically this line https://github.com/sveltejs/svelte-atom/blob/1b2dbd6e14681365988a6798599e18b7887a38fb/grammars/svelte.cson#L26

This file is ported from sveltejs/language-tools https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.src.yaml. The injection already doesn't quite work in the atom so it has been partially rewritten to supported in the atom. Is there any difference between the implementation of the atom and GitHub backend?

We can try to debug the problem and see if we can find a solution on our end. But maybe we can revert to the old version? Or I have another fork version forked from before we rewrote to use injection [here](https://github.com/jasonlyu123/SvelteVisualStudio/blob/main/SvelteVisualStudioShared/Grammars/svelte.tmLanguage.json). Maybe that's also an option?

**Comment by lildude** [comment] 2022-07-26 15:53
> Is there any difference between the implementation of the atom and GitHub backend?

Yes. Linguist processes and "compiles" the grammar files using our [grammar "compiler"](https://github.com/github/linguist/tree/master/tools/grammars) and creates a single JSON file which is then ready by the syntax highlighter.

You can see the current result of this "compiler" in the `source.svelte.json` in the `linguist-grammars.tar.gz` tarball attached to all releases - I suspect you'll be able to spot the problems when you see the resulting file. This precisely the file the highlighter uses.

**Comment by kindoflew** [comment] 2022-07-28 14:26
would it be possible to use Svelte's official VSCode grammar from here?: https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.src.yaml

(especially considering that Atom is basically done out here?)

i don't really know anything about TextMate grammars, but I've been following this issue around several repos ever since I first noticed it, so I'm trying to help where i can 😅.

**Comment by lildude** [comment] 2022-07-28 14:31
> would it be possible to use Svelte's official VSCode grammar from here?: https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.src.yaml

Yup, that should work too.

**Comment by umanghome** [comment] 2022-10-27 08:05
I'm working on updating the VS Code grammar to make it usable with linguist.
