### ISSUE TITLE
Blade highlighting bug

### ISSUE THREAD

**Issue by RonMelkhior** [github/linguist#3185] opened 2016-09-01 21:33 UTC
There's a bug with the syntax highlighting for Blade. end calls are not highlighted, as seen here:

![GitHub](https://i.clouds.tf/iw38/c4al.png)

But the vendor package for Blade, which I use in Atom, highlights it properly:

![Atom](https://i.clouds.tf/r0xk/1x8w.png)

Makes me believe it's a bug with Linguist, since I use the exact same vendor package in Atom.

Cheers,
Ron.

**Comment by pchaigno** [comment] 2016-09-04 19:38
GitHub and Atom use different engines for regular expressions in grammars (Oniguruma vs. PCRE). Because of this there are some discrepancies between the two.

I checked for some of the differences I know (for instance GitHub requires [explicit count modifiers](https://github.com/bro/bro-sublime/pull/1)) but couldn't find the issue. The author of the grammar might be better suited to find the origin of the bug.

If the author is not ready to support GitHub's parser (that might be the case if his grammar was designed solely for Atom), we could switch to a new grammar, if there's one better.

**Comment by pchaigno** [comment] 2016-09-10 13:26
Closing in favor of jawee/language-blade#53. If the bug is fixed upstream, we'll automatically include the fix in our next release.

**Closed by pchaigno** 2016-09-10 13:26 UTC

**Comment by Alhadis** [comment] 2016-09-15 13:59
[Fixed](https://github.com/jawee/language-blade/issues/54).

**Comment by RonMelkhior** [comment] 2016-09-22 08:28
@pchaigno Hi Paul, was this update deployed?

**Comment by pchaigno** [comment] 2016-09-22 09:32
Yes, it should be deployed with the last release (from 5 hours ago).
@arfon ?

**Comment by RonMelkhior** [comment] 2016-09-22 10:29
If it was deployed, the issue was not fixed.

```blade
@if ($errors->first())
	<div class="row">
		<div class="sixteen wide widescreen sixteen wide computer sixteen wide tablet sixteen wide mobile column">
			<div class="ui negative message">
				<div class="header">
					There's been an error.
				</div>
				<ul class="list">
					@foreach ($errors->all() as $error)
						<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
		</div>
	</div>
@endif
```

**Comment by arfon** [comment] 2016-09-22 15:05
> If it was deployed, the issue was not fixed.

Ugh. In my late-night deploying I completely forgot to update the upstream grammars 😫

**Comment by arfon** [comment] 2016-09-23 04:40
OK I just cut a new gem. Is this looking better again now?

**Comment by RonMelkhior** [comment] 2016-09-23 04:41
Yes, it works now 👍

**Comment by arfon** [comment] 2016-09-23 04:42
:+1: thanks for confirming!
