### ISSUE TITLE
KiCAD project now being labelled as SourcePawn.

### ISSUE THREAD

**Issue by John-Nagle** [github/linguist#3812] opened 2017-09-05 07:10 UTC
The project at

    https://github.com/John-Nagle/ttyloopdriver

has been properly identified as a KiCAD electronic design for months. But after some changes made today, it's now identified as "SourcePawn". This is apparently some strange scripting language for HalfLife (that's still around?). I'd really like to not see my hardware designs associated with a game. Thanks.

It may be the addition of this file, which is a LTSpice device definition for a depletion-mode MOSFET, that caused problems. 

https://github.com/John-Nagle/ttyloopdriver/blob/master/circuitsim/dn2535.lib

**Comment by 5N44P** [comment] 2017-09-07 01:10
Let's see if i can help you with something. 
Recently i've had the same problem that you have with Kicad repos (except for the SourcePawn thing)
A few weeks ago some corrections were made on the KiCad language definition, here on the Linguist. 
(See #3765 and #3743)
It was misclassified as a programming language, now it's classified as data. 
(See #3784 and #3795 for more explanations). 
This raised some problems that, for what I could understand, afflict Linguist for a long time. Such as the possibility to show a non-programming language in the stats of a repo. 

Now, some of us, @seppestas in particular, become intrested in trying to fill this deficency. (See #3805)  
At the moment there is a PR pending (#3807), that probably would address this problem. 
We hope that it will be examined by github staff and linguist contributors soon 

About your SourcePawn problem: for what I can see, the file that it's being misrecognized is this: 
https://github.com/John-Nagle/ttyloopdriver/blob/master/circuitsim/NSI45030AT1G.SP
Maybe you should consider to move it to a vendored code path, as suggested by the troubleshooting section of the readme. 

But for the reasons above, this would not fix the issue with kicad not being recognized (which actually is being recognized, but isn't being counted for language stats), it will only remove "SourcePawn" from your language stats.

**Comment by seppestas** [comment] 2017-09-07 09:56
Hey @John-Nagle, it looks like the "LTspice Encrypted File" in your repo got erroneously recognised as a SourcePawn file (like @5N44P already pointed out).

I couldn't find a lot of info on this type of file. Could you tell me:

- Where you got the file from?
- If the SP extension is only used for "Encrypted Files" within LTSpice or also for other purposes? I found [some mention on it being used for netlists](https://courses.engr.illinois.edu/ece464/fa2017/ltspice/ltspice_help.pdf#page=48), but I'm not sure if this means it is always an encrypted netlist.
- If you can use an other extension for the same file?

As @5N44P already mentioned, the reason your repo is not recognised as being a KiCad project is because KiCad files are since recently classified as data instead of programming files. There is a request to have this fixed (for KiCad and other project files) in #3805.

**Comment by John-Nagle** [comment] 2017-09-08 04:23
Info about encrypted .sp file:

- It's from ON Technology. It's the simulation file for circuits using this part: https://www.onsemi.com/pub/Collateral/NSI45030A-D.PDF (Two-terminal current regulator, sort of like a Zener for current. $0.31 each.) 

- Whether files for LTSpice are encrypted are not is independent of the suffix. I think .lib and .sub files can also be encrypted. 

- As it turns out, in the current design, I'm not using that part any more, and can delete the file.

So I deleted the file, and now the project is being identified as "AGS Script". Aargh!

**Comment by John-Nagle** [comment] 2017-09-08 04:27
I tried adding a .gitattributes file to the root of the project:

    *.kicad-pcb linguist-language=KiCad
    *.pro linguist-language=KiCad
    *.sch linguist-language=KiCad
    *.kicad_mod linguist-language=KiCad

No effect.

**Comment by 5N44P** [comment] 2017-09-08 09:55
You can se which files are being recognized as such from here: 
https://github.com/John-Nagle/ttyloopdriver/search?l=ags-script
As we stated before, kicad won't be recognized in the language bar anymore, and unfortunately there's no manual override for that, unless the PR from seppestas is approved

**Comment by John-Nagle** [comment] 2017-09-09 22:52
The AGS-Script recognizer needs work. AGS-Script is a C-like language. The file Linguist tagged as AGS-Script starts:

    Version 4
    SHEET 1 1932 744
    WIRE 1264 -384 976 -384
    WIRE 1264 -368 1264 -384
    WIRE 1264 -368 1232 -368
    WIRE 752 -304 736 -304
    ...

Not even close.

**Comment by lildude** [comment] 2017-09-10 07:00
> Not even close.

Yes, this misclassification can happen as the files have an extension (.asc) shared by multiple languages so a combination of the heuristics and the final "if all else fails, let's take an educated guess" naive Bayesian classifier were needed to try determine the language. In this case it guessed AGS-Script as it was the closest it could get as it will never return nothing (known limitation).

I'm not sure what language this should be detected as but we'd accept a PR to correctly identify these files, assuming there's enough in the wild usage. 

Until then, you'll need to manually over ride the language like you've done for your other files, which I can confirm, contrary to what you said above, _has_ worked... the files _are_ being correctly classified as KiCad, for example https://github.com/John-Nagle/ttyloopdriver/search?utf8=✓&q=extension%3Akicad_pcb+NOT+hack&type=, but as they're now considered data, not a programming language, don't count as part of the language stats.

The pending PR would likely allow you to override this, and may be approved once my colleagues who are more familiar with the direction GitHub plans to take the language identification part of the website. It's potentially a major product decision so it may take a while to be approved, so please bare with us.

**Comment by John-Nagle** [comment] 2017-09-10 16:51
A classifier that returns some random result when nothing is a good match is unusual. Classifiers usually return some measure of confidence, and below some threshold, that's usually treated as "unrecognized". An "unidentified" project type would be better than the current rather random results.

**Comment by seppestas** [comment] 2017-09-10 17:35
I think the main issue here is the important files, i.e KiCad schematic, layout and project files and SPICE scripts not being counted in the language statistics. If they would have been included, the mis-recognized files would have a way smaller impact on the repo. This is why I created #3805.

Since the SPICE models come from external sources, I think it's a good idea to mark them as "vendored". This can be done using the .gitattributes file, and it will cause Linguist not to include the files in the language statistics.

**Comment by Alhadis** [comment] 2017-09-10 17:39
SPICE scripts? What are those?

**Comment by John-Nagle** [comment] 2017-09-10 18:23
SPICE is a simulator for analog electronics, originally developed decades ago at U.C. Berkeley. There are LTSpice (from Linear Technology) and PSpice variants. A SPICE simulation will have a schematic file, suffix .asc, which looks like this:

    Version 4
    SHEET 1 880 680
    WIRE 64 80 -48 80
    WIRE 320 80 192 80
    ...
    SYMBOL voltage -48 64 R0
    SYMATTR SpiceLine Rser=1
    SYMATTR InstName V1
    SYMATTR Value 125

Case doesn't matter. Any useful schematic file must have some WIRE, SYMBOL, and SYMATTR lines. So those should be easy to recognize. Those files were written by hand in the early days, but now they're usually created and edited in GUI programs. 

A SPICE simulation may have some component models. These are usually written by humans. A typical SPICE model for a diode:

    .MODEL ZC830A D IS=5.355E-15 N=1.08 RS=0.1161 XTI=3
    + EG=1.11 CJO=19.15E-12 M=0.9001 VJ=2.164 FC=0.5
    + BV=45.1 IBV=51.74E-3 TT=129.8E-9
    + ISR=1.043E-12 NR=2.01
    *NOTES: FOR RF OPERATION ADD PACKAGE INDUCTANCE 0F 2.5E-9H AND SET
    *RS=0.68 FOR 2V, 0.60 FOR 5V, 0.52 FOR 10V OR 0.46 FOR 20V BIAS.

These appear in .lib and .sub files, and sometimes .txt.  Commands begin with "." They will have a ".MODEL" or ".SUBCKT" line. Lines beginning with "+" are continuations, and lines beginning with "*" are comments. Parentheses are sometimes used to group sections of parameters.

There are also .asy files, which define new schematic symbols. These look like

    Version 4
    SymbolType CELL
    RECTANGLE Normal 64 48 -64 -32
    SYMATTR Value TL783C
    SYMATTR Prefix X
    SYMATTR Value2 TL783c
    SYMATTR Description TL783C voltage regulator
    SYMATTR ModelFile tl783c.sub
    PIN -64 0 LEFT 8
    PINATTR PinName IN
    PINATTR SpiceOrder 1

and are usually edited in GUI programs. There should be SYMATTR, PIN, and PINATTR lines.

So that's how to recognize the various SPICE files.

**Comment by Alhadis** [comment] 2017-09-10 18:49
Ah, I see! =) That's a very insightful and helpful response, thank you for sharing. 😀  I was a bit mislead by the term (SPICE) "Script", which left me expecting something which resembled a list of executable commands. If so, that would classify as a "programming"-type language and we could look into adding it to Linguist.

**Comment by John-Nagle** [comment] 2017-09-10 19:56
It's sometimes taught to EE students as a language. Here's a manual.[1] They use a .cir suffix. The GUI versions add more features so schematics can be drawn well, but the basic statements are a form of programming. It's declarative, like XML or YAML, rather than executable. If you see those keywords in .cir or .asc, flag them as SPICE source. 

[1] https://www.cpp.edu/~prnelson/courses/ece220/220-spice-notes.pdf

**Comment by Alhadis** [comment] 2017-09-10 23:35
I'll need to look into this. I should add SPICE to [`language-pcb`](https://github.com/Alhadis/language-pcb) for a start, which will involve research on the format's syntax and composition. Will then browse GitHub to gauge if SPICE simulator files are widely-used enough on the site.

Once I have a pull-request together, I'll be needing your help to review how I've arranged things, since I certainly don't trust my understanding of PCB-related technology. Even less after the recent kerfuffle. 😜

**Comment by seppestas** [comment] 2017-09-11 09:00
SPICE in not only used in PCB design, originally it was intended to be used in IC design (it's even in the name, Simulation Program with *Integrated Circuit Emphasis*). In reality I don't think SPICE in its pure form is still used that much in IC design, typically it is only used as a backend and in combination with other tools (and I don't think anyone will publish an IC design on Github any time soon).

Either way, classifying SPICE as a "PCB" language might be a bit of a long stretch. Maybe we could rename it to "EDA" (Electronic Design Automation) languages, a more general term that includes both PCB and IC design (but that term might not be that commonly known).

**Comment by Alhadis** [comment] 2017-09-11 09:44
Hrm, no... it sounds like we should classify SPICE as simply `SPICE`, to be honest. I'm afraid you'll need to wait a bit before I can begin reading up on it. Have my hands tied at the moment. 😞

**Comment by lildude** [comment] 2018-01-26 13:31
The changes introduced in https://github.com/github/linguist/pull/3807 are now live on GitHub.com so I think we can close this issue.

Happy overriding peeps 🎉

**Closed by lildude** 2018-01-26 13:31 UTC
