### ISSUE TITLE
Include submodules in repo language calculations

### ISSUE THREAD

**Issue by controversial** [github/linguist#3229] opened 2016-09-18 00:22 UTC
When calculating the primary language of a repo or the percentages, I think there should be an option somewhere to include submodules. For example, one of my projects is divided into frontend, backend, and client. Each of these is in its own repo, and I have [a conglomerate repo](https://github.com/pythonista-cloud/pythonista-cloud) containing everything as submodules. Because it contains only submodules, it doesn't show languages in the top bar, nor does it show a language where it's pinned to my profile.

For the simplest case, when all the submodules are also hosted on GitHub, this could be a  fairly inexpensive calculation.

I understand that some people include external libraries as submodules, which is why I propose this as a configurable option in the repo.

Thoughts from anyone?

**Comment by arfon** [comment] 2016-10-01 02:34
> Thoughts from anyone?

I am sympathetic to this use case but I think it's pretty niche to be honest. In addition, we'd have to be really careful to make sure people didn't create repositories with nested submodules (i.e. A has submodule B, B has submodule C, C has submodule D etc..). I'm afraid I can't really imagine us doing this sorry so rather than leave the issue open I think we should close this as a `#wontfix`

**Closed by arfon** 2016-10-01 02:34 UTC

**Comment by Alhadis** [comment] 2016-10-01 05:00
Just stick a dummy file in there:

```python
#!/usr/bin/env python
from subprocess import call

# Update Git submodules
call(["git", "submodule", "update"])
```

Both your submodules are already 100% Python, so having a 112-byte throwaway script will still give an accurate indication of your repo's content.

**Comment by controversial** [comment] 2016-10-01 13:16
@arfon I don't think it's really too niche, lots of people have submodules even if their one repo isn't empty. But I guess I see your point

@Alhadis There are actually 3 submodules, one of which is HTML/CSS/JS (`server/static`)

If you guys feel like this is too niche, I respect that though.

**Comment by sschuberth** [comment] 2017-03-16 16:04
> For the simplest case, when all the submodules are also hosted on GitHub, this could be a fairly inexpensive calculation.

Exactly, which is why I believe at least this case should be implemented, as I don't see how this would introduce a lot of complications. You simply rely on what the GitHub API already reports as languages for the submodule paths and take that as given into account.

**Comment by sschuberth** [comment] 2017-03-16 16:06
BTW, this seems to be a duplicate of https://github.com/github/linguist/issues/1205.

**Comment by controversial** [comment] 2017-03-16 16:07
You're right, it is a duplicate.

**Comment by softmarshmallow** [comment] 2020-10-12 09:19
Why would we do this? I'de like to exclude submodule's language on my repository. written module ts -> dist gives js, whole repository telling that it's js. (*R*)

**Comment by lildude** [comment] 2020-10-12 09:41
> I'de like to exclude submodule's language on my repository.

@softmarshmallow This is already the case. Submodules are _never_ considered when assessing a repository's language statistics. If you're seeing unexpected languages, it's likely some other file(s) within your repo is being incorrectly detected. Feel free to open a new issue and we can help you identify the responsible files.

**Comment by softmarshmallow** [comment] 2020-10-12 09:44
@lildude  Hi, thanks. could you take a quick look? I think it's a bug. when i click js, no files will appear.
It was 100% ts, after adding submodule it got js.

https://github.com/bridgedxyz/assistant

Just to confirm the case. once confirmed, I'll open a new issue.

**Comment by lildude** [comment] 2020-10-12 09:45
Can you please open a new issue so keep that discussion separate from this issue.

**Comment by softmarshmallow** [comment] 2020-10-12 09:47
@lildude #5043 thanks.
