### ISSUE TITLE
report an error during add-grammar

### ISSUE THREAD

**Issue by hwdef** [github/linguist#4862] opened 2020-05-12 03:04 UTC
## Preliminary Steps

Please confirm you have...
- [X] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [X] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [X] considered implementing an [override](https://github.com/github/linguist#overrides),
- [X] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

when I run the shell in https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language ,I received a error.

OS: archlinux
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

```shell
$ script/add-grammar https://github.com/kulics-works/vscode-k                                   
Checking docker is installed and running
$ docker ps
Registering new submodule: vendor/grammars/vscode-k
$ git submodule add -f https://github.com/kulics-works/vscode-k vendor/grammars/vscode-k
$ script/grammar-compiler add vendor/grammars/vscode-k
Confirming license
$ script/licensed --module /home/edward/code/ruby/linguist/vendor/grammars/vscode-k
  > /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- bundler/setup (LoadError)
  >     from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
  >     from script/licensed:3:in `<main>'
Command failed. Aborting.
```

**Comment by lildude** [comment] 2020-05-12 07:08
Looks like you're missing the bundler gem, specifically v1.x. Have you installed all the dependencies and followed the "Getting Started" instructions at the beginning of the file.

If you have, this could be something specific to archlinux or Ruby 2.7.0 neither of which have been formerly tested as GitHub doesn't use either, especially Ruby 2.7 which is very new.

As an aside, unless you've found a way to address the other problems detailed in previous attempts like https://github.com/github/linguist/pull/3689, your PR isn't likely to get much traction.

**Comment by hwdef** [comment] 2020-05-12 08:04
@lildude 
Thanks for your reply. I solved the problem.

And thanks for your suggestion ,I noticed #3689, I think I should make some changes abount our language.How about creating a pr first?If there's any thing wrong, we can discuss it in PR.

**Comment by lildude** [comment] 2020-05-12 08:10
Go for it, but be warned, if you're proposing the addition of the `.k` extension, you're in for a tough battle as it is very popular across many many languages and will be the biggest hurdle to get over.

**Comment by hwdef** [comment] 2020-05-12 08:12
@lildude 
Thank you for your reminder. My friend and I have also noticed this problem. We are discussing to change it and try not to let this problem bother you.

**Comment by hwdef** [comment] 2020-05-12 09:27
@lildude 
I encountered another error,Can you give me some help?

```shell
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [17:14:20] 
$ bundle install
Fetching gem metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Fetching version metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Fetching dependency metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Resolving dependencies...
Using rake 13.0.1
Using public_suffix 4.0.5
Using addressable 2.7.0
Using bundler 1.10.0
Using byebug 11.1.3
Using charlock_holmes 0.7.7
Using coderay 1.1.2
Using color_difference 0.0.1
Using color-proximity 0.2.1
Using dotenv 2.7.5
Using escape_utils 1.2.1
Using multipart-post 2.1.1
Using faraday 1.0.1
Using mini_mime 1.0.2
Using rugged 0.99.0

NoMethodError: undefined method `[]' for nil:NilClass
An error occurred while installing github-linguist (7.9.0), and Bundler cannot continue.
Make sure that `gem install github-linguist -v '7.9.0'` succeeds before bundling.


# edward @ edward-pc in ~/code/ruby/linguist on git:master x [17:22:27] C:5
$ gem list | grep github
github-linguist (7.9.0)
```

**Comment by lildude** [comment] 2020-05-12 10:29
🤔 you're mixing up two different methods of installing the gem.

You appear to have already installed it globally and are then attempting to use bundler to install it again and this is the step that's failing.

What happens if you use `script/bootstrap` as documented?  

Try updating your version of bundler too - v1.10.0 is very old.

**Comment by hwdef** [comment] 2020-05-13 01:41
thanks for you help .Here is the complete output.

```shell
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:36:42] 
$ script/licensed --module /home/edward/code/ruby/linguist/vendor/grammars/vscode-k
Could not find gem 'minitest (>= 5.0) ruby' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:36:44] C:7
$ bundle install                                                                   
Fetching gem metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Fetching version metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Fetching dependency metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Resolving dependencies...
Using rake 13.0.1
Using public_suffix 4.0.5
Using addressable 2.7.0
Using bundler 1.10.0
Using byebug 11.1.3
Using charlock_holmes 0.7.7
Using coderay 1.1.2
Using color_difference 0.0.1
Using color-proximity 0.2.1
Using dotenv 2.7.5
Using escape_utils 1.2.1
Using multipart-post 2.1.1
Using faraday 1.0.1
Using mini_mime 1.0.2
Using rugged 0.99.0

NoMethodError: undefined method `[]' for nil:NilClass
An error occurred while installing github-linguist (7.9.0), and Bundler cannot continue.
Make sure that `gem install github-linguist -v '7.9.0'` succeeds before bundling.
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:36:49] C:5
$ gem install github-linguist -v '7.9.0'                                           
Building native extensions. This could take a while...
Successfully installed github-linguist-7.9.0
Parsing documentation for github-linguist-7.9.0
Done installing documentation for github-linguist after 0 seconds
1 gem installed
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:36:54] 
$ bundle install                                                                   
Fetching gem metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Fetching version metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
/home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Fetching dependency metadata from https://rubygems.org/./home/edward/.gem/ruby/2.7.0/gems/bundler-1.10.0/lib/bundler/fetcher/dependency.rb:70: warning: URI.escape is obsolete
.
Resolving dependencies...
Using rake 13.0.1
Using public_suffix 4.0.5
Using addressable 2.7.0
Using bundler 1.10.0
Using byebug 11.1.3
Using charlock_holmes 0.7.7
Using coderay 1.1.2
Using color_difference 0.0.1
Using color-proximity 0.2.1
Using dotenv 2.7.5
Using escape_utils 1.2.1
Using multipart-post 2.1.1
Using faraday 1.0.1
Using mini_mime 1.0.2
Using rugged 0.99.0

NoMethodError: undefined method `[]' for nil:NilClass
An error occurred while installing github-linguist (7.9.0), and Bundler cannot continue.
Make sure that `gem install github-linguist -v '7.9.0'` succeeds before bundling.
```



And if i update bundler,I will have other errors.

```shell
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:39:03] C:5
$ gem update bundle
Updating installed gems
Nothing to update
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:39:21] 
$ gem update bundler
Updating installed gems
Updating bundler
Fetching bundler-2.1.4.gem
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Installing ri documentation for bundler-2.1.4
Installing darkfish documentation for bundler-2.1.4
/usr/lib/ruby/gems/2.7.0/gems/rdoc-6.2.0/lib/rdoc/generator/darkfish.rb:588: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/fileutils.rb:206: warning: The called method `mkdir_p' is defined here
/usr/lib/ruby/gems/2.7.0/gems/rdoc-6.2.0/lib/rdoc/generator/darkfish.rb:591: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/fileutils.rb:303: warning: The called method `ln' is defined here
/usr/lib/ruby/gems/2.7.0/gems/rdoc-6.2.0/lib/rdoc/generator/darkfish.rb:597: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/fileutils.rb:426: warning: The called method `cp' is defined here
Done installing documentation for bundler after 4 seconds
Parsing documentation for bundler-2.1.4
Done installing documentation for bundler after 1 seconds
Gems updated: bundler
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:39:45] 
$ script/licensed --module /home/edward/code/ruby/linguist/vendor/grammars/vscode-k
Could not find gem 'minitest (>= 5.0)' in any of the gem sources listed in your Gemfile.
Run `bundle install` to install missing gems.
# edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:40:06] C:7
$ bundle install
Fetching gem metadata from https://rubygems.org/..............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.10)

  Current Bundler version:
    bundler (2.1.4)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.10)' in any of the relevant sources:
  the local ruby installation
```

**Comment by lildude** [comment] 2020-05-13 08:35
I'll start with the end and work backwards:

> And if i update bundler,I will have other errors.

This is because you've updated to bundler v2. We're limited to v1 due to `licensed`.

You'll need to uninstall v2 and install v1, eg `gem uninstall --version 2.1.4 && gem install bundler -v "~>1.0"`

Going further back in your response...

> Here is the complete output.
> 
> ```shell
> # edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:36:42] 
> $ script/licensed --module /home/edward/code/ruby/linguist/vendor/grammars/vscode-k
> Could not find gem 'minitest (>= 5.0) ruby' in any of the gem sources listed in your Gemfile or available on this machine.
> Run `bundle install` to install missing gems.
> # edward @ edward-pc in ~/code/ruby/linguist on git:master x [9:36:44] C:7
> $ bundle install  
> [...]
> ```

If you're following the instructions in CONTRIBUTING.md, you shouldn't be running `script/licensed` manually. It happens automatically for you. If you're having problems, it's likely a step before in the process had a problem or hasn't been run. 

This is where I think the problem is. You've either _not_ run the very first step in [Getting Started](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#getting-started) or you encountered problems running the `script/bootstrap` script. I know this because that is what installs all the dependencies for subsequent steps and scripts like `script/licensed`.

Have you `script/bootstrap` as documented and as I suggested before? 

If not, please remove bundler v2 and install v1 as suggested above and then run the script.

If you have, please remove bundler v2 and install v1 as suggested above and then run the script again and if you encounter problems, provide the full output from the failure.

**Comment by hwdef** [comment] 2020-05-14 06:18
@lildude 

Thank you for your patient answers,it is my mistake.

I started directly from step [Adding a language](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) and skipped step [Getting started](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#getting-started).

After following your suggestion, I got the correct result.
If I solve the problem of the name, I will create a PR.
After a preliminary discussion, my friend and I thought that `kulang` was a good name, and the language file suffix was `.ku`,what do you think?

**Comment by lildude** [comment] 2020-05-14 08:23
Good to hear you've got things working now.

> After a preliminary discussion, my friend and I thought that `kulang` was a good name, and the language file suffix was `.ku`,what do you think?

That could work, but remember the language and extension needs to meet our minimum popularity requirement in order for it to be accepted and the PR merged.

**Comment by hwdef** [comment] 2020-05-14 08:43
@lildude 
Yes, I also noticed this problem. And I checked #4777. I think our repositories has not reached the required quantity. When the quantity meets the requirements, I will create a pr.

Thanks again, I think we can close this issue now.

**Closed** 2020-05-14 08:46 UTC
