### ISSUE TITLE
dotfile syntax definition

### ISSUE THREAD

**Issue by stevenvachon** [github/linguist#3717] opened 2017-07-10 21:27 UTC
```
VAR1=value
VAR2=value
```
 would be nice

**Comment by Alhadis** [comment] 2017-07-10 22:29
... uh. Hello? You okay there, mate?

What are you talking about, exactly?

**Comment by stevenvachon** [comment] 2017-07-10 22:52
Hello. Requesting the addition of a syntax highlighter.

**Comment by Alhadis** [comment] 2017-07-10 23:03
For which language? What are `env/`, `.env/`, and `./dotenv`? Languages, dotfiles configs...?

**Comment by stevenvachon** [comment] 2017-07-10 23:53
yes, dotfile configs.

**Comment by Alhadis** [comment] 2017-07-11 00:03
"Dotfiles" could mean any filetype, really. Basically, they're a bunch of directory/project-level configuration settings where one is written in JSON, another using Shell-Script exports, or even XML data.

There's nothing binding these filetypes together other than they all start with a dot, and they're considered important in some manner.

**Comment by stevenvachon** [comment] 2017-07-11 00:45
[dotenv](https://npmjs.com/dotenv)

**Comment by Alhadis** [comment] 2017-07-11 00:59
Okay, so... you're referring to a very particular .file, then.

Reading the [description of that NPM module](https://www.npmjs.com/package/dotenv#should-i-commit-my-env-file) in its readme tells me there aren't going to be many `*.env` files on GitHub:

> ### Should I commit my .env file?
> No. We **strongly** recommend against committing your .env file to version control. It should only include environment-specific values such as database passwords or API keys. Your production database should have a different password than your development database.

Now, having said all that, you can feel free to submit a pull request to have `.env` files recognised - if you're able to convince us beforehand that there actually *are* many hundreds of users uploading their ENV keys (which I sorely doubt there will be, given the tone of `dotenv`'s readme...)

**Comment by pchaigno** [comment] 2017-07-11 06:38
@Alhadis You're assuming people read docs: https://github.com/search?p=1&q=extension%3Aenv+DB_HOST&type=Code&utf8=%E2%9C%93. Now, should we really encourage that? Is there a legitimate reason to commit these files?

**Comment by Alhadis** [comment] 2017-07-11 06:52
Uh, you're right. If anything, this would actually make it easier for people to look up sensitive information that shouldn't have been published. :| Anything-`localhost` is obviously harmless, but who knows what else other people have committed...

**Comment by stevenvachon** [comment] 2017-07-11 13:05
You don't need to have a `.env` file committed to necessitate a syntax definition. There are code blocks within readme files, for example. Also, `.env.sample` files get committed.

**Comment by Alhadis** [comment] 2017-07-11 13:08
Confirmed. Nobody reads documentation anymore. 😢 

@stevenvachon I encourage you to read [`CONTRIBUTING.md`](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language) for the reasons why this won't go through... simultaneously the reason why we *do* indeed require `.env` files to be committed in numerous repositories before it can be formally recognised on GitHub (which is also what determines syntax highlighting).

**Comment by pchaigno** [comment] 2017-07-11 13:13
@Alhadis They might be enough `.env` files for addition... I'm more worried about the numerous conflicts with other use of the `.env` extension.

**Comment by stevenvachon** [comment] 2017-07-11 13:14
Pretty well any application that has a database uses `.env` files for development. Not all will document its usage, but more should. Feel free to do a readme search of all repos (including private ones) on GitHub to find your hundreds of instances.

**Comment by Alhadis** [comment] 2017-07-11 13:19
Should we classify `.curlrc` files too, then? Those are definitely more widespread, and need syntax highlighting much more than `.env` files, from what I gather...

**Closed** 2017-07-11 13:22 UTC
