### ISSUE TITLE
Language rename: GAS and Groff

### ISSUE THREAD

**Issue by larsbrinkhoff** [github/linguist#2382] opened 2015-05-04 07:39 UTC
When language renaming becomes possible, I suggest these:

`GAS` → `Unix Assembly`
_GAS_ is the GNU implementation of the Unix _as_ assembler.  The `.s` file extension isn't tied specifically to _gas_.

`Groff` → `troff`
_groff_ is the GNU implementation of the traditional Unix (or even older) typesetting software _troff_ (and _nroff_).  See https://www.gnu.org/software/groff/manual/html_node/History.html.

**Comment by larsbrinkhoff** [comment] 2015-05-12 09:46
Also, for similar reasons:

`Bison` → `Yacc`

**Comment by yegortimoschenko** [comment] 2015-05-21 18:30
> `Groff` → `troff`

While `troff` is definitely better than `Groff` (the latter is ridiculous) the language is called `roff`, as pointed [in Wikipedia](http://en.wikipedia.org/wiki/Roff) and [in the manpage](http://mdocml.bsd.lv/man/roff.7.html).

So, instead, it should be:

> `Groff` → `roff`

/cc @larsbrinkhoff

**Comment by larsbrinkhoff** [comment] 2015-05-22 11:06
Before submitting this issue, I read various documents, and it was not clear to me that `roff` is the obvious name for the language.  For one thing, it's described as a predecessor to `troff` and `nroff.

But I have nothing against `roff`, if that's what people want.

**Comment by yegortimoschenko** [comment] 2015-05-26 15:02
@larsbrinkhoff Here are more sources that prove that the language name is `roff`:

* [groff(7) manpage](http://linux.die.net/man/7/groff) — see the title
* [FreeBSD roff(7) manpage](http://howtounix.info/man/FreeBSD/man7/roff.7)

`troff` is just one of numerous implementations of `roff`. There is `nroff` as well, for example.

**Comment by bentley** [comment] 2015-07-23 16:49
Yes, `roff` is the correct name. See also [mandoc’s roff(7) manual](http://mdocml.bsd.lv/man/roff.7.html) and [History of UNIX Manpages](http://manpages.bsd.lv/history.html).

**Comment by Alhadis** [comment] 2015-08-31 10:24
I have to agree. `Groff` is no more a different language to `troff` as GhostScript is to PostScript. Furthermore, both implementations share the same roots in `roff`, which is the original root of the typesetting language. So choosing one over the other doesn't really make sense.

**Comment by yegortimoshenko** [comment] 2016-03-15 12:04
@Alhadis I have never seen it in uppercase. It is just `roff`.

**Comment by Alhadis** [comment] 2016-03-15 12:14
Yeah, I'm currently developing a language package for Roff for Atom... and after extensive research into the language's history, I can tell you I fully agree. Must've been fooled by the capitalisation of a `.TH` statement somewhere. =)

**Comment by pchaigno** [comment] 2016-12-04 15:17
Closing in favor of #3278.

**Closed by pchaigno** 2016-12-04 15:17 UTC
Labels: Language rename

**Comment by yegortimoshenko** [comment] 2016-12-04 15:58
@pchaigno Please reopen. The issue is only partially solved, `Groff` is now `troff`, which is not more correct than `roff`.

**Comment by Alhadis** [comment] 2016-12-04 15:59
@yegortimoshenko Wrong. `troff` is short for "Typesetter roff", pronounced `tee-roff`. It's the name of an interpreter, not the language.

**Comment by yegortimoshenko** [comment] 2016-12-04 16:02
@Alhadis That's the issue I'm talking about. It's like calling C language `gcc`. Fortunately, that's not the case. `troff` should be renamed into `roff`, the latter of which is the correct name of the format.

**Comment by Alhadis** [comment] 2016-12-04 16:03
Ah wait, sorry, I misread you. I interpreted that as _"we should name this `troff`, not `roff`."_

Disregard.

**Comment by Alhadis** [comment] 2016-12-04 16:04
That's also the name that we're going with; see #3278.

**Comment by yegortimoshenko** [comment] 2016-12-04 16:11
Sorry, didn't see 673aeb32b9851cc58429c4b598c876292aaf70c7, only 247439b8e2f9285fc2adc2238868ae32048dffad. My soul can finally rest in peace :-)

**Comment by Alhadis** [comment] 2016-12-04 16:11
So can mine. =)
