### ISSUE TITLE
Support the TLA+ specification language

### ISSUE THREAD

**Issue by pron** [github/linguist#2693] opened 2015-10-19 09:30 UTC
File suffix .tla

**Comment by pchaigno** [comment] 2015-11-14 18:00
See the [contribution guidelines for adding support for a new language in Linguist](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#adding-a-language). If TLA+ meets the requirement, I can help you prepare a pull request for it ;)

**Comment by johnyf** [comment] 2015-11-14 19:17
It seems unlikely that there are hundreds of [TLA+](http://research.microsoft.com/en-us/um/people/lamport/tla/tla.html) users on GitHub yet. It is a language for describing and proving system correctness, so (unfortunately) it is not used as widely as it should. Nonetheless, there is usage by several accounts, which appears to justify supporting it:

https://github.com/jameshfisher/tlaplus
https://github.com/joewilliams/tla_tools
https://github.com/weituo12321/Asynchronous_Systems
https://github.com/BackupTheBerlios/e3t
https://github.com/thanhhai1302/TLA_Z3
https://github.com/hhu-stups/tlatools
https://github.com/lemmy/tlaplus
https://github.com/xingchaoet/TLAPlus
https://github.com/pron/wildfire-challenge
https://github.com/pron/amazon-snapshot-spec

**Comment by pchaigno** [comment] 2015-11-14 20:42
I'm not from GitHub so in the end the decision will be @arfon's or @bkeepers'.

FYI: I count 54 repositories distributed among 44 users in the [first 1,000 files of this GitHub search](https://github.com/search?q=extension%3Atla+EXTENDS+OR+CONSTANTS&ref=reposearch&utf8=%E2%9C%93). There are probably a little more than a hundred repositories using TLA+. I also didn't notice any other language using that same extension.

@johnyf @pron Do you know a grammar (TextMate or Atom bundle or Sublime Text package) that could be used to highlight TLA+ files?

**Comment by johnyf** [comment] 2015-11-14 20:54
Thanks for the more refined search.

I found the following syntax highlight definitions:

- [atom](https://github.com/wysiib/language-tla-pluscal)
- [vim](https://github.com/vim-scripts/TLA)
- [textadept](https://github.com/Hackerpilot/textadept-TLA-)

**Comment by johnyf** [comment] 2015-11-14 20:57
The syntax of TLA+ is defined in Chapter 15 of [Specifying systems](http://research.microsoft.com/en-us/um/people/lamport/tla/book.html) by Leslie Lamport (available as PDF).

**Comment by pchaigno** [comment] 2015-11-15 07:27
Seems that [wysiib/language-tla-pluscal](https://github.com/wysiib/language-tla-pluscal) also supports PlusCal syntax. Do you know what extension PlusCal files use?

**Comment by johnyf** [comment] 2015-11-15 10:21
Algorithms written in [PlusCal](http://research.microsoft.com/en-us/um/people/lamport/tla/pluscal.html) are placed within a comment inside a `.tla` file. The algorithmic description is then automatically translated to TLA+, and inserted by the translator in a pre-designated area within the same file. [This is an example](https://github.com/jameshfisher/tlaplus/blob/master/examples/N-Queens/QueensPluscal.tla) for the N-queens problem. It is described explicitly in the [c-version of the PlusCal manual](http://research.microsoft.com/en-us/um/people/lamport/tla/c-manual.pdf), Sec.2.2, p.8.

I am not sure whether this makes highlighting more difficult, because it may introduce context sensitivity.

**Comment by agentultra** [comment] 2016-05-05 11:18
Added support in https://github.com/github/linguist/pull/2981 with a search result 115 users and >3k source code files.

**Comment by johnyf** [comment] 2016-05-09 04:22
#2990 has been merged and [appears](https://github.com/agentultra/TLAGrammar/blob/7e351a9cdf6fbf3132e35246ce190bad237fb39c/TLA.tmbundle/Syntaxes/TLA.tmLanguage) to add support for TLA+, but not PlusCal (which can be included within a TLA+ file).

Should this issue remain open until PlusCal be supported, or closed?

**Comment by pchaigno** [comment] 2016-06-28 22:09
@johnyf Sorry for the late reply :bow: 

Highlighting PlusCal algorithms within TLA+ files will depend on the syntax highlighting definition. Do you know one that might be able to do that? (The one currently used and the Atom's above do not seem to be capable of that :/)

**Comment by johnyf** [comment] 2016-06-28 22:18
As observed [above](https://github.com/github/linguist/issues/2693#issuecomment-156788330), https://github.com/wysiib/language-tla-pluscal supports pluscal, and that would need to be converted from an Atom grammar to a linguist grammar. Also, it will somehow need to be defined as part of TLA+, or as an extension of TLA+ (I think the latter may be cleaner, though I don't have experience with linguist grammars).

I am currently adding some missing parts to the TLA+ syntax grammar that linguist uses, forked over here: https://github.com/johnyf/TLAGrammar

**Comment by pchaigno** [comment] 2016-06-28 22:40
> As observed above, https://github.com/wysiib/language-tla-pluscal supports pluscal, and that would need to be converted from an Atom grammar to a linguist grammar.

That's what I though, but [it doesn't seem to highlight the PlusCal part when in a comment](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_url=https%3A%2F%2Fgithub.com%2Fwysiib%2Flanguage-tla-pluscal%2Fblob%2Fmaster%2Fgrammars%2Ftla.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fjameshfisher%2Ftlaplus%2Fblob%2Fmaster%2Fexamples%2FN-Queens%2FQueensPluscal.tla&code=).

> (I think the latter may be cleaner, though I don't have experience with linguist grammars).

Actually, github.com can use Atom, Sublime Text or TextMate grammars directly ;)

> I am currently adding some missing parts to the TLA+ syntax grammar that linguist uses, forked over here: https://github.com/johnyf/TLAGrammar

Awesome! We'll catch those in the next release of Linguist, after they're merged in @agentultra's grammar :smiley:

**Comment by johnyf** [comment] 2016-09-08 17:44
I have encountered the following issue with writing TLA+ expressions in GitHub issues, and wondering what should be the right way to approach it. Spacing in TLA+ is meaningful, like in Python, but even more, in that *alignment* has meaning. In particular, this is important when writing conjunctions and disjunctions, which is one of the most useful aspects of TLA+ (Lamport discusses it first in [this paper](http://link.springer.com/article/10.1007/BF01211870)). For example:

```tla
FormulaA /\ \/ FormulaB
            \/ FormulaC
```

The vertical alignment of the disjuncts `FormulaB` and `FormulaC` has meaning. The problem is that in GitHub's editor for comments in issues, obtaining the above is nearly impossible to do visually. The reason is that the font used within the editor has different width for spaces than for other characters. So, the 12 characters from the start of the first line to the start of `\/` have to be *counted*, and as many spaces (12) be inserted on the second line before `\/ FormulaC`. This is very cumbersome, and so not viable for everyday use, especially with long formulae, which are the forte of TLA+.

What would be the right way to approach this? Is there an approach to changing the font used within GitHub's editor? Of course, the simplest solution is to write the answer in an external editor, then copy/paste it here, but this is somewhat less practical for everyday use.

**Comment by agentultra** [comment] 2016-09-09 14:45
@johnyf There might be a couple of options:

1. Configure your browser settings to use a fixed-width font in text boxes
2. Use a plugin/extension for your browser that will allow you to edit text box content using your editor of choice

**Comment by pchaigno** [comment] 2018-08-04 16:09
Closing. Support for TLA landed in v4.8.5.

**Closed by pchaigno** 2018-08-04 16:09 UTC
