### ISSUE TITLE
Identifies main language as COBOL but no files identified as written in COBOL

### ISSUE THREAD

**Issue by gkobilansky** [github/linguist#2434] opened 2015-06-03 01:13 UTC
Repo shows as 38.8% written in COBOL - https://github.com/wealthbot-io/wealthbot
Click on COBOL, shows 'We couldn't find any code matching ''' - https://github.com/wealthbot-io/wealthbot/search?l=cobol

**Comment by pchaigno** [comment] 2015-06-03 21:59
The statistics aren't always in sync with the search page (it's a cache update issue). Looks like the issue is fixed now :zap:

**Closed** 2015-06-04 17:23 UTC
