### ISSUE TITLE
Jison/Jisonlex files no longer highlighted correctly on GitHub

### ISSUE THREAD

**Issue by nwhetsell** [github/linguist#4649] opened 2019-09-17 14:44 UTC
## Preliminary Steps

Please confirm you have...
- [x] reviewed [How Linguist Works](https://github.com/github/linguist#how-linguist-works),
- [x] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,
- [x] considered implementing an [override](https://github.com/github/linguist#overrides),
- [x] verified an issue has not already been logged for your issue ([linguist issues](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+repo%3Agithub/linguist)).

## Problem Description

Jison/Jisonlex highlighting seems to be incorrect on GitHub. Here’s an example on GitHub:

https://github.com/cdibbs/language-jison/blob/master/spec/sample.jison

And here’s the same file on Lightshow:

https://github-lightshow.herokuapp.com/?utf8=✓&scope=source.jison&grammar_format=auto&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fcdibbs%2Flanguage-jison%2Fmaster%2Fspec%2Fsample.jison

Lightshow appears to be running Linguist v7.3.1. If GitHub is running Linguist v7.6.0 or later, this may be related to PR #4595.

**Comment by Alhadis** [comment] 2019-09-17 15:03
#4595 didn't touch Jison highlighting, so the problem likely stems from the author's embedding of the `source.lex` scope somewhere.

In either case, this is an upstream issue that should be filed at the appropriate repository, not here.

**Comment by nwhetsell** [comment] 2019-09-17 15:17
Thanks for the swift reply!

The repository is https://github.com/cdibbs/language-jison, but a pretty big hunk of it is [from me](https://github.com/cdibbs/language-jison/graphs/contributors). So, while I can file an issue there, I’m almost certainly going to be the one to have to fix it anyway. I’ll also understand if this issue must be closed if it’s determined that this simply can’t be an issue with Linguist.

I’m happy to be wrong about this, but as far as I can tell, `source.lex` doesn’t appear in any of the [Jison grammars](https://github.com/cdibbs/language-jison/tree/master/grammars). There are inclusions of `source.js` and `source.jisonlex`, however. Could the inclusion of `source.jisonlex` be the issue?

**Comment by Alhadis** [comment] 2019-09-17 15:49
> Could the inclusion of `source.jisonlex` be the issue?

I doubt it. I noticed the grammar is using injections; keep in mind they're not handled 100% consistently by GitHub's highlighter (the `injectionSelector` field in particular is unsupported, according to #3924).

Also, could you be a bit more specific about which parts in particular are incorrectly highlighted?

**Comment by nwhetsell** [comment] 2019-09-17 16:05
I was under the impression that the `injectionSelector` field had been whitelisted: https://github.com/cdibbs/language-jison/issues/17#issuecomment-364936784. At any rate, that part of the grammar seems to be working. The highlighting of `yytext` in line 9 of [language-jison/spec/sample.jison](https://github.com/cdibbs/language-jison/blob/7b43e22b09775c8e6424cbf937f2fe34a848f1f5/spec/sample.jison) is coming from that `injectionSelector`:

<img width="238" alt="Screen Shot 2019-09-17 at 11 56 50 AM" src="https://user-images.githubusercontent.com/14102861/65058437-3f06f400-d942-11e9-815f-97727039818d.png">

The part of a Jison file that’s incorrectly highlighted is everything after the first section break denoted by `%%` (including the section break). For example, here’s lines 37–68 of [language-jison/spec/sample.jison](https://github.com/cdibbs/language-jison/blob/7b43e22b09775c8e6424cbf937f2fe34a848f1f5/spec/sample.jison) on GitHub:

<img width="606" alt="Screen Shot 2019-09-17 at 12 02 37 PM" src="https://user-images.githubusercontent.com/14102861/65058887-0ca9c680-d943-11e9-808b-e0a5fa5996b3.png">

And here’s the same thing on Lightshow:

<img width="575" alt="Screen Shot 2019-09-17 at 12 03 50 PM" src="https://user-images.githubusercontent.com/14102861/65059010-3a8f0b00-d943-11e9-9736-a641532860c4.png">

**Comment by Alhadis** [comment] 2019-09-17 16:32
Okay, so this is certainly an issue on GitHub's end. There's no reason that should be working in Lightshow and not on GitHub's side.

I also noticed ordinary Lex files [aren't receiving](https://github.com/Alhadis/language-grammars/blob/76947d5366baed12c357196806a2aae9774501e0/tests/c.lex) syntax highlighting *at all*, indicating that something very wrong is happening with Lightshow...

/cc @lildude

**Comment by lildude** [comment] 2019-09-17 16:48
Whooops. I've clearly forgotten to update Lightshow 😊. I'll add it to my TODO list.

**Comment by Alhadis** [comment] 2019-09-17 16:51
There's still the matter of the highlighting discrepancies; in particular, the missing Lex highlighting added in the last release...

**Comment by lildude** [comment] 2019-09-17 16:57
> There's still the matter of the highlighting discrepancies; in particular, the missing Lex highlighting added in the last release...

🤔 the language is getting selected correctly so something's gone awry with picking up the grammar itself.

**Comment by lildude** [comment] 2019-10-03 13:31
I've taken a look into this as this appears to only affect languages or grammars added in v7.6.0. Work is underway to improved the syntax highlighting service used by GitHub and I suspect it has missed the v7.6.0 update. I've opened an issue to bring this to the attention of the team responsible for the improvements.

I'll update when I know more or when things are working as expected again.

**Comment by lildude** [comment] 2019-10-03 16:06
Re: 

> I also noticed ordinary Lex files aren't receiving syntax highlighting at all, indicating that something very wrong is happening with Lightshow...

... this ...
> Work is underway to improved the syntax highlighting service used by GitHub and I suspect it has missed the v7.6.0 update.

... was indeed the case.

The original issue is however unrelated, that's still a grammar issue. I'll try update Lightshow in the next few days.

**Comment by lildude** [comment] 2020-04-22 05:37
I've hit a road block with updating Lightshow that is going to require some dedicated time to resolve. As this isn't related to this issue, I'm going to close this issue more.

**Comment by nwhetsell** [comment] 2020-04-22 11:54
I understand that closing this issue is entirely up to Linguist, but I’m not sure that this is a grammar issue, and if it is a grammar issue I’m not sure how to determine what the issue is.

I first noticed this issue after GitHub started using Linguist [v7.6.0](https://github.com/github/linguist/releases/tag/v7.6.0), around the end of Aug 2019. (Jison files were definitely highlighted correctly on GitHub before then. Some of my pull requests to Jison grammars were about improving highlighting on GitHub, for example https://github.com/cdibbs/language-jison/pull/8 (merged in May 2017), and it wouldn’t have made sense to make improvements to syntax highlighting on GitHub if that wasn’t working at all.)

One possibility [mentioned in a comment](https://github.com/github/linguist/issues/4649#issuecomment-532262220) on this issue is the presence of a `source.lex` scope in a Jison grammar. The problem there is that `source.jison`, `source.jisonlex`, and `source.js` are used in Jison grammar `include`s, but not `source.lex`. Running

```sh
pattern="include:\\s*[\"']source\\.\\w+"
base_URL=https://raw.githubusercontent.com/cdibbs/language-jison/v2.12.0/grammars

file=jison.cson
curl --remote-name --show-error --silent $base_URL/$file
egrep $pattern $file
```

shows 12 `include`s:

```
        # Simply setting the patterns object to {include: "source.jisonlex"}
                    patterns: [include: "source.jisonlex#user_code_section"]
                patterns: [include: "source.jisonlex#rules_section"]
            patterns: [include: "source.jisonlex#definitions_section"]
      {include: "source.js"}
        patterns: [include: "source.js"]
        patterns: [include: "source.js"]
        patterns: [include: "source.js"]
        patterns: [include: "source.js#string_escapes"]
        patterns: [include: "source.js#string_escapes"]
        patterns: [include: "source.js#string_escapes"]
        patterns: [include: "source.js"]
```

Then running:

```sh
file=jisonlex.cson
curl --remote-name --show-error --silent https://raw.githubusercontent.com/cdibbs/language-jison/v2.12.0/grammars/$file
egrep $pattern $file
```

shows 15 `include`s:

```
      {include: "source.jison#comments"}
      {include: "source.jison#include_declarations"}
          {include: "source.jison#comments"}
          {include: "source.jison#comments"}
      {include: "source.jison#options_declarations"}
      {include: "source.jison#user_code_blocks"}
      {include: "source.jison#comments"}
        patterns: [include: "source.jison#user_code_blocks"]
          {include: "source.jison#include_declarations"}
          {include: "source.js"}
      {include: "source.jison#user_code_include_declarations"}
      {include: "source.js"}
      {include: "source.jison#comments"}
      {include: "source.jison#quoted_strings"}
      {include: "source.js#string_escapes"}
```

There are no `include`s in the [one remaining grammar file]( https://github.com/cdibbs/language-jison/blob/v2.12.0/grammars/jisonlex-injection.cson). The upshot is that it doesn’t seem like the issue is `source.lex` scopes in Jison grammars.

It’s probably also worth noting that syntax highlighting seems to work fine in Atom when both [language-grammars](https://atom.io/packages/language-grammars) and [language-jison](https://atom.io/packages/language-jison) are installed:

<img width="1748" alt="Screen Shot 2020-04-22 at 7 48 58 AM" src="https://user-images.githubusercontent.com/14102861/79978510-08f89800-846e-11ea-8f73-340c8e1568f6.png">

Again, I completely understand that it’s up to Linguist to determine whether this is a Linguist issue, but I’d be grateful for any guidance on where to look for what’s breaking syntax highlighting of Jison grammars on GitHub.

**Comment by lildude** [comment] 2020-04-22 13:45
🤔 I thought this was resolved already.

You raise some interesting points and I'm starting to wonder if this is due to a change around the new syntax highlighting service (it provides its own Javascript grammar) or a change to the `source.js` pulled in by other grammars. The former started just before v7.6.0 was released and v7.6.0 included an update to the Javascript grammar.

I'll reopen this and see if I can find some time to dig into this.

**Comment by Alhadis** [comment] 2020-04-22 13:50
I knew Tree Sitter was going to cause trouble sooner or later... 😜

**Comment by lildude** [comment] 2020-04-22 17:33
I ran a local instance of Lightshow in which I've updated the gem to 7.6.1 (I picked up where I left off after getting stuck as reported earlier in this issue) and the syntax highlighting has changed:

![Screenshot 2020-04-22 at 18 27 48](https://user-images.githubusercontent.com/627280/80013684-3291dd80-84c7-11ea-9ec8-865a40dd4b77.png)

It's not quite as reported originally, but confirms there is definitely a change and suggests this is due to a change in the grammars shipped with 7.6.1 (they're the same as v7.6.0) and not the new highlighter service.

I'll see if I can pin-point the grammar tomorrow, but my suspicion is the Javascript grammar.

Sidenote: I'm closer to updating Lightshow too as fresh eyes have cleared the road block I initially encountered.

**Comment by lildude** [comment] 2020-04-27 16:57
Lightshow has now been updated to Linguist v7.9.0 and it shows proper syntax highlighting for Jison. I'll look into where this is getting messed up some time this week or early next.

**Comment by nwhetsell** [comment] 2020-04-27 17:43
Awesome, thank you for looking into this!

**Comment by maxbrunsfeld** [comment] 2020-04-28 17:48
This looks like a bug in GitHub's TextMate grammar engine. Lightshow uses an older version than GitHub.com, but there haven't been too many changes.

**Comment by maxbrunsfeld** [comment] 2020-04-28 18:29
Ok, after a bit more bisecting, I have determined that the change was caused by this change: https://github.com/textmate/textmate/pull/1437. GitHub maintains a private fork of the TextMate highlighting engine, but that ☝️ PR backports a fix that we made into TextMate upstream.

The problem is explained in more detail in that PR, but the TLDR is that the jison or jisonlex grammar contains one or more invalid rules that have a `patterns` property but no `end` property.

Previously, a rule like that would *work*, but it would cause the syntax highlighter to go into a performance death spiral. Now, the `patterns` property is ignored, in order to maintain acceptable performance.

[Here](https://github.com/cdibbs/language-jison/blob/7b43e22b09775c8e6424cbf937f2fe34a848f1f5/grammars/jison.cson#L35) [are](https://github.com/cdibbs/language-jison/blob/7b43e22b09775c8e6424cbf937f2fe34a848f1f5/grammars/jison.cson#L39) two examples of the problem in `language-jison`. There may be others. Sorry for the disruption that this caused. When making this change, we tried to search for examples of the problematic rules in all of the grammars, but we must have missed jison.

I opened this issue on the upstream Jison grammar repo: https://github.com/cdibbs/language-jison/issues/21.

**Closed by maxbrunsfeld** 2020-04-28 18:29 UTC

**Comment by lildude** [comment] 2020-04-29 09:26
I've now updated Lightshow to use the same version as GitHub.com and confirmed it shows the issue with the original grammar too now.

The update coming in https://github.com/cdibbs/language-jison/pull/22 now renders correctly too: [new grammar](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgithub.com%2Fcdibbs%2Flanguage-jison%2Fblob%2F9d4cb4b044832320a51fabb6e533fc299425f552%2Fgrammars%2Fjison.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fcdibbs%2Flanguage-jison%2Fmaster%2Fspec%2Fsample.jison&code=)
