### ISSUE TITLE
CSS files not displayed in stats (not even as `other`)

### ISSUE THREAD

**Issue by honzi** [github/linguist#2442] opened 2015-06-06 23:28 UTC
Hello. It looks like the CSS files in the https://github.com/iterami/Engine.htm repository aren't being displayed in the language statistics, despite existing https://github.com/iterami/Engine.htm/search?l=css. I thought it would be because they are small compared to the JavaScript files, but I've noticed that this often makes languages get grouped in an `other` category so I'm not sure if this is a bug or not.

**Comment by pchaigno** [comment] 2015-06-07 08:26
The statistics of your repository are not up-to-date. I get this when running the last version of Linguist against your repository:
```
$ linguist
95.11%  JavaScript
4.33%   HTML
0.56%   CSS
```
It's probably an issue with the cache. You can contact support@github.com to fix it.

**Comment by gjtorikian** [comment] 2015-06-07 19:40
I busted the cache, but it changed nothing. 

Since the CSS files allocate so few bytes compared with the other two languages, they won't show up in the language bar. 

I'm marking this as "not a bug," mostly because we've been talking internal about how to handle more accurate representations on the language bar.

**Closed by gjtorikian** 2015-06-07 19:40 UTC
