### ISSUE TITLE
Why not add a local file to create my own syntax?

### ISSUE THREAD

**Issue by jarriztg** [github/linguist#3292] opened 2016-10-25 09:56 UTC
I wanna create a file .gitcolors or whatever XD and make my own syntax in a local file, to add a local syntax if I want my colors in my script *.format.

Maybe that isn't here (i dont know) but really that will be fantastic! :)

**Comment by pchaigno** [comment] 2016-10-25 11:55
This looks like a duplicate of #2627.

**Closed** 2016-10-25 12:50 UTC
