### ISSUE TITLE
C# code being displayed as Smalltalk in language statistics

### ISSUE THREAD

**Issue by Iwuh** [github/linguist#3474] opened 2017-02-14 22:09 UTC
https://github.com/Iwuh/IwuhSelfbot You can see here that although all the code in my repo is C#, Github says that it's 33.5% Smalltalk.

**Comment by pchaigno** [comment] 2017-02-15 05:33
This is the same bug as #353:
```
bundle exec linguist ../IwuhSelfbot/IwuhSelfbot/src/IwuhSelfbot/Commands/Services/EmojiService.cs
/linguist/lib/linguist/blob_helper.rb:281:in `split': invalid byte sequence in UTF-8 (ArgumentError)
	from /linguist3/lib/linguist/blob_helper.rb:281:in `lines'
	from /linguist3/lib/linguist/blob_helper.rb:298:in `loc'
	from /linguist3/bin/linguist:59:in `<top (required)>'
	from /var/lib/gems/2.3.0/bin/linguist:23:in `load'
	from /var/lib/gems/2.3.0/bin/linguist:23:in `<main>'
```
You can use [Linguist overrides](https://github.com/github/linguist#overrides) to fix it locally.

**Comment by Caged** [comment] 2017-05-03 21:28
Going to close this as a dupe of #353. Thanks for the report!

**Closed by Caged** 2017-05-03 21:28 UTC
