### ISSUE TITLE
Pascal: need highlight of '#'+number

### ISSUE THREAD

**Issue by Alexey-T** [github/linguist#5153] opened 2021-01-19 11:29 UTC
The Delphi/FreePascal support syntax of character with its ASCII code:
```
#10 //means chr(10)
#200 //chr(200)
#0 //null char
#$ABCD //chr(0xABCD) with hex notation - max 4 digits
```
Current highlight don't support it
![bug](https://user-images.githubusercontent.com/4154978/105028974-cac2f000-5a62-11eb-837b-2ab13c4787f4.png)

@artem3213212

**Comment by lildude** [comment] 2021-01-19 12:22
🤔 I'm sorry to inform you but your haste to open this (and the other two) issue and ignoring the "Preliminary Steps" in the template and links within has resulted in you wasting some of your precious time.

This is clear because the second checkbox is:

> - [ ] reviewed the [Troubleshooting](https://github.com/github/linguist#troubleshooting) docs,

The third point in that document tells you where you should have logged this issue... hint, it's in **bold** letters, and it's not this repo 😉

Please review the Troubleshooting documentation and open a ticket in the correct repo.

If and when the issue is resolved, it'll be pulled into Linguist and thus GitHub.com, the next time a full (not patch) release is made.

I'm closing this issue as this is the wrong location for this issue.

**Closed by lildude** 2021-01-19 12:22 UTC
