### ISSUE TITLE
The C code is longer than Ruby/Batchfile but it's included in "Other" category.

### ISSUE THREAD

**Issue by Yilmaz4** [github/linguist#5428] opened 2021-06-14 14:54 UTC
I maked a simple Hello World program in all possible languages, I created the Ruby code earlier and C code later. But even C code is longer than Ruby code, it's still included in Other category and I want visitors to see "C" language in Languages section instead of Batchfile. Is this a bug or something I don't know?

This is [my repository](https://github.com/Yilmaz4/Hello-World/)

**Comment by lildude** [comment] 2021-06-14 15:43
GitHub will only show at most 6 languages in the side bar, and it'll show the six most popular by bytes of code. The rest will be grouped into "Other". You're seeing Batchfile instead of C because you have more bytes of Batchfile code than C:


    C# 3.91 KB
    Visual Basic .NET 3.63 KB
    Java 3.21 KB
    Python 2.98 KB
    Ruby 2.68 KB
    Batchfile 2.54 KB
    C++ 2.24 KB
    C 2.01 KB
    F# 64 Bytes
    Shell 29 Bytes
    BASIC 23 Bytes


As this isn't a bug and is expected behaviour, I'm moving this to Discussions.

**Closed** 2021-06-14 15:44 UTC
Labels: Bug
