### ISSUE TITLE
LInguist is reporting my project as a Jupyter Notebook

### ISSUE THREAD

**Issue by adam704a** [github/linguist#3316] opened 2016-11-03 19:28 UTC
As you can see, I have some notebooks, but mostly this is a python project.

https://github.com/ICTatRTI/researchnet

Did I do something wrong?

**Comment by TotalVerb** [comment] 2016-11-04 12:18
Jupyter notebooks have an inflated number of lines of code, since they store a lot of metadata. So it doesn't take many notebooks to "take over" a project.

**Comment by Alhadis** [comment] 2016-11-04 12:23
Does anybody actually write these files out by hand? Because it seems like they're generated primarily from a webapp.

And if that's the case, well, I'd say these generated files should be marked as exactly that: generated.

/cc @pchaigno /resident Python-guy

**Comment by TotalVerb** [comment] 2016-11-04 12:32
Whatever action is taken, it would be best to maintain the searchability and identifiability of [notebook-only](https://github.com/sunlightlabs/fcc-net-neutrality-comments) repositories.

**Comment by TotalVerb** [comment] 2016-11-04 12:35
Possibly the best course of action is to modify the lines of code reported into an "equivalent lines of code" measure which takes into account the unavoidable boilerplate. For instance, the source line consisting of the single character `π` may turn into this monstrosity in the .ipynb file:

```julia
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "π = 3.1415926535897..."
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "π"
   ]
  },
```

**Comment by Alhadis** [comment] 2016-11-04 12:38
That thing is about as long as the value's floating-point component itself.

All we'd need to mark these things as generated is to match against a common pattern that's consistently used in webapp-created notebooks. Usually it's something like `Generated by AppName 1.1.1.1.1.1-betasemverasfuck0` or what-have-you.

**Comment by TotalVerb** [comment] 2016-11-04 12:40
You could maybe match against

```json
 "metadata": {
  [ stuff in here varies ]
 },
 "nbformat": 4,
 "nbformat_minor": 1
```

but wouldn't this make notebook-only repositories classify incorrectly?

**Comment by Alhadis** [comment] 2016-11-04 12:48
Marking them as generated simply omits them from the language-statistics bar. We already have a [number of generated-file detection routines](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb) that filter files that would otherwise unfairly skew a repository's stats. [Here's the logic](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L235-L256) for detecting generated PostScript, for example. You can imagine how many projects would be incorrectly classified as PostScript if we left every `.eps` file unchecked.

And while that snippet you've posted might work, it should ideally be 100% unambiguous. E.g., the rules that test against single-line patterns are all very specific:

* [`Generated by Cython`](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L355-L366)
* [`# This file is automatically generated by Racc`](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L399-L410)
* [`/* The following code was generated by JFlex`](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L412-L423)
* [`// This is a generated file. Not intended for manual editing.`](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L425-L437)

Et cetera.

**Comment by TotalVerb** [comment] 2016-11-04 12:53
The difference between postscript and Jupyter is that all Jupyter notebooks are "generated", though (either by the web app or by IPython's CLI).

Here are some empty, newly-created notebooks with Julia and Python kernels.

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Julia 0.5.0",
   "language": "julia",
   "name": "julia-0.5"
  },
  "language_info": {
   "file_extension": ".jl",
   "mimetype": "application/julia",
   "name": "julia",
   "version": "0.5.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
```

and 

```json
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "anaconda-cloud": {},
  "kernelspec": {
   "display_name": "Python [conda root]",
   "language": "python",
   "name": "conda-root-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
```

**Comment by TotalVerb** [comment] 2016-11-04 12:57
For what it's worth, I think personally that a good solution would be to estimate how many lines of a Jupyter notebook are "source" and how many are "generated". Source lines (which are all written by a human) generally look like this:

```json
   "source": [
    "import Base: +\n",
    "\n",
    "+{T<:Number}(x::DualNumber{T}, y::DualNumber{T}) = DualNumber{T}(x.re + y.re, x.ep + y.ep)\n",
    "\n",
    "DualNumber(10.0, 17.0) + DualNumber(5.0, 9.0)"
   ]
```

**Comment by soniclavier** [comment] 2016-11-29 06:12
I am having the same problem, I have about 3-4 .ipynb files out of 144 files(mainly java and scala) in my repo. If there is any option to make Linguist report based on count of files rather than size, it would be helpful.

**Comment by Caged** [comment] 2017-05-03 23:08
:wave: It looks like the [original repo](https://github.com/ICTatRTI/researchnet) is no longer classified as an ipython notebook and I don't see a `.gitattributes` file in the repo.  Can someone clarify if this is still an issue?

**Comment by lildude** [comment] 2017-10-31 15:11
As @Caged mentioned, things appear to be working now on the original repo. As there hasn't been an update since 3 May, I'm closing this on the basis this has been resolved.

**Closed by lildude** 2017-10-31 15:11 UTC

**Comment by pierluigiferrari** [comment] 2017-11-08 16:55
@lildude I can confirm that things are *not* working regarding Jupyter notebooks. It's still the same issue as before: A Jupyter notebook consists of Python code that the author wrote, and of generated code simply to display the notebook in a browser. The generated code usually makes up a lot more lines than the Python code.

The first problem here is that for the purpose of what linguist is trying to achieve (i.e. a breakdown of the programming languages the author used in the repo) "Jupyter notebook" should not be considered a language at all. For all intents and purposes it's just a container that holds Python code. The second problem is that simply ingoring Jupyter notebooks from the statistics also ignores all of the actually relevant Python code inside them.

**Comment by lildude** [comment] 2017-11-08 18:07
Thanks for confirming this and for the explanation @pierluigiferrari.  Now I have a better understanding having looked into it, and given your two points, I don't think this is something that can easily, if ever, be addressed automatically.

The biggest limiting factor that I can see is the fact the Jupyter notebooks combine written and generated language within the same file. Linguist doesn't support partial file classification and isn't likely to ever do so as I'd imagine this would be incredibly resource intensive and probably highly unreliable when it comes to even attempting to differentiate between human and computer written code within the same file. Our current classifier is already hugely inefficient as it is.

The next limiting factor is preference. Some want the Jupyter note books recognised for what they are, others prefer them to be identified by the language they're written themselves and others still don't want the files counted at all.

I think our current implementation (implemented in https://github.com/github/linguist/pull/2746 via https://github.com/github/linguist/pull/2763) combined with manual overrides is probably the best compromise for all.  

Jupyter note books are also far too prevalent on GitHub to change the default behaviour without major backlash.

**Comment by Alhadis** [comment] 2017-11-08 18:16
> Linguist doesn't support partial file classification and isn't likely to ever do so as I'd imagine this would be incredibly resource intensive and probably highly unreliable when it comes to even attempting to differentiate between human and computer written code within the same file.

... which is where an idea of mine may hold the answer. ;) I regurgitated [sleep-deprived explanations](https://github.com/github/linguist/pull/3743#issuecomment-318821134) which, through weighting averages assigned to specific scopes, could yield a more rational Python Notebook usage. E.g., the number of lines the programmer actually *did* pen of their own hand.

**Comment by pierluigiferrari** [comment] 2017-11-08 19:15
@lildude I understand. As you said, it seems like the best solution is for Jupyter notebook users to use manual override. Thanks for clarifying why it is the way it is and why it will likely remain this way!

**Comment by pierluigiferrari** [comment] 2017-11-08 19:15
@lildude I understand. As you said, it seems like the best solution is for Jupyter notebook users to use manual override. Thanks for clarifying why it is the way it is and why it will likely remain this way!

**Comment by pierluigiferrari** [comment] 2017-11-08 19:16
@lildude I understand. As you said, it seems like the best solution is for Jupyter notebook users to use manual override. Thanks for clarifying why it is the way it is and why it will likely remain this way!

**Comment by Borda** [comment] 2019-03-18 21:34
> @lildude I understand. As you said, it seems like the best solution for Jupyter notebook users is to use manual override. Thanks for clarifying why it is the way it is and why it will likely remain this way!

What does it mean the manual override for language statistic on GitHub? Is it the `.gitatributes` file?
In my opinion, it would be fair counting if for the ipynb lines will be counted only the source lines, not all metadata as well as all generated outputs...

**Comment by pchaigno** [comment] 2019-03-19 05:50
@Borda Please see the last paragraph of [how Linguist works](https://github.com/github/linguist/blob/master/README.md#how-linguist-works) and [Linguist overrides](https://github.com/github/linguist/blob/master/README.md#overrides).
