### ISSUE TITLE
Rename Nimrod to Nim

### ISSUE THREAD

**Issue by phase** [github/linguist#2381] opened 2015-05-04 00:22 UTC
[Nimrod](http://nim-lang.org/) has been renamed to `Nim`, and Linguist still recognizes it as [`Nimrod`](https://github.com/docopt/docopt.nim).

**Comment by pchaigno** [comment] 2015-05-04 04:36
That is not possible currently but should change in the near future:
https://github.com/github/linguist/issues?q=nimrod+is%3Aclosed+sort%3Aupdated-desc
(see the comments in the first one for more information)

**Comment by phase** [comment] 2015-05-04 04:38
Darn, I hope this gets fixed soon!

**Comment by pchaigno** [comment] 2015-05-04 04:39
Me too ;)

**Comment by arfon** [comment] 2015-05-04 13:19
Yeah, this is a dupe of this sorry: https://github.com/github/linguist/pull/1936

I'm tracking these requests with the `Language Rename` label

**Closed by arfon** 2015-05-04 13:19 UTC
