### ISSUE TITLE
sql seems recognized but not counted

### ISSUE THREAD

**Issue by robmuh** [github/linguist#2673] opened 2015-10-06 17:27 UTC
Just did a quick http://github.com/skilstak/db repo and happened to notice it thinks it is all makefile, but when I click on the languages it shows SQL with the overwhelming majority. Wondering why SQL isn't making it into the overall repo language summary.

**Comment by pchaigno** [comment] 2015-10-06 20:14
Only programming and markup languages are counted for the statistics.
Currently, SQL is not considered a programming language. The issue is that if it is, many projects will be incorrectly recognized as SQL projects. Not sure was a solution would be...

**Comment by arfon** [comment] 2015-10-07 09:03
Yeah, I'm afraid those languages marked as `data` (as [SQL is](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L3044)) aren't counted in repository statistics.

**Closed by arfon** 2015-10-07 09:03 UTC

**Comment by yangsoosong** [comment] 2018-09-24 18:53
You can now [override](https://github.com/github/linguist/blob/master/README.md#detectable) language definitions and file paths. You just need to make sql detectable for linguist library.
Adding *.sql linguist-detectable=true in .gitattributes solved this issue for me!
