### ISSUE TITLE
Add Mikrotik RouterOS script

### ISSUE THREAD

**Issue by zainarbani** [github/linguist#5874] opened 2022-04-24 12:34 UTC
## Language name
[Mikrotik RouterOS Script](https://wiki.mikrotik.com/wiki/Manual:Scripting)

## URL of example repository
[https://github.com/Detavern/rspm](https://github.com/Detavern/rspm)
[https://github.com/Disassembler0/mikrotik-scripts](https://github.com/Disassembler0/mikrotik-scripts)
[https://github.com/eworm-de/routeros-scripts](https://github.com/eworm-de/routeros-scripts)
[https://github.com/massimo-filippi/mikrotik](https://github.com/massimo-filippi/mikrotik)
[https://github.com/zainarbani/wms](https://github.com/zainarbani/wms)
[github search extension:rsc put](https://github.com/search?q=extension%3Arsc+put&type=code)

## URL of syntax highlighting grammar
[https://github.com/Kentzo/MikrotikScript/blob/master/MikrotikScript.tmLanguage](https://github.com/Kentzo/MikrotikScript/blob/master/MikrotikScript.tmLanguage)

## Most popular extensions

`.rsc`

## Detected language
`Rascal`

**Comment by Nixinova** [comment] 2022-04-24 20:40
See #5442

**Comment by lildude** [comment] 2022-04-25 07:17
Closing as duplicate of https://github.com/github/linguist/issues/5442

**Closed by lildude** 2022-04-25 07:17 UTC
Labels: Add Language, Good First Issue
