### ISSUE TITLE
Inconsistent syntax highlighting

### ISSUE THREAD

**Issue by BaerMitUmlaut** [github/linguist#3031] opened 2016-05-31 20:39 UTC
Not sure if this the correct repository to create the issue at, but we noticed some inconsistent SQF syntax highlighting today over @acemod.

For example, compare the `then`s in this file:
https://github.com/alganthe/Co-ops/blob/dev_altis/functions/vehicle_handler/fn_vehiclePFH.sqf
In all lines but line 53, the `then` is black while it should be red. You can notice the same behavior in the example file of the [original PR that added SQF support](https://github.com/github/linguist/pull/1415/files).

**Comment by pchaigno** [comment] 2016-05-31 20:44
Linguist only selects the grammar to use for highlighting. For SQF, GitHub uses [JonBons/Sublime-SQF-Language](https://github.com/JonBons/Sublime-SQF-Language/tree/777931999d391173c509018fd38e4d124063f13d). You should open an issue there if there isn't already one ;)

**Comment by BaerMitUmlaut** [comment] 2016-05-31 21:08
Thank you for the quick response. I assume this file is used?
https://github.com/JonBons/Sublime-SQF-Language/blob/master/SQF.tmLanguage
From what I can see it just contains a list of keywords, so I'm not sure how sometimes the highlighting works, and sometimes it doesn't. This package also seems to work perfectly fine in Sublime Text:

![highlighting-sqf](https://cloud.githubusercontent.com/assets/9693842/15690529/3aa92766-2784-11e6-9ae9-2a397f23bfb2.png)

**Comment by BaerMitUmlaut** [comment] 2016-05-31 21:28
I've managed to trigger it on purpose:
```SQF
// broken
if (true) then {
    [] call fncDummy
} else {
    [] call fncDummy
};

// working
if (true
) then {
    [] call fncDummy
} else {};

// broken twice
if (true) then {} else {};
```
It looks like it only recognizes one keyword per line:
```SQF
true
false
not true
not false
true and false
true && false
```

**Comment by Alhadis** [comment] 2016-05-31 22:25
Already spotted one mistake in the grammar:
```
invoke|nil|not|or|pi|preprocessFile|private|private1|private2|private3|private4|private5|private6|private7|private8|private9|spawn|step|switch|then|this|throw|to|true|try|while|with|)\b</string>
```
Right at the very end, there:
```
with|)\b</string>
```
The stray `|` is saying "Yeah, apply this rule anyway, even if nothing matches".

**Comment by Alhadis** [comment] 2016-05-31 22:40
@BaerMitUmlaut I can't reproduce the highlighting bug in Lightshow. [As you can see](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=source.sqf&grammar_url=&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Falganthe%2FCo-ops%2Fblob%2Fdev_altis%2Ffunctions%2Fvehicle_handler%2Ffn_vehiclePFH.sqf&code=), it has no problems highlighting each instance of the keyword `then`.

This leads me to believe the faulty regex *is* to blame, because different highlighting engines will handle recursion errors differently. GitHub's highlighting is handled by a slightly different engine to the one being used by Lightshow (although they're related). Which would also explain why Sublime Text isn't having any difficulties, either.

Sending a pull request.

**Comment by Alhadis** [comment] 2016-05-31 23:24
Okay, never mind. I spoke too soon: if I test my fix in Lightshow, the bug occurs. If I use the original grammar, nothing happens.

The hell.

**Comment by arfon** [comment] 2016-06-01 16:30
> Linguist only selects the grammar to use for highlighting. For SQF, GitHub uses JonBons/Sublime-SQF-Language. You should open an issue there if there isn't already one ;)

Closing this as it's an upstream issue (and not one that can be fixed in Linguist). @BaerMitUmlaut - please file an issue on the grammar repository and we'll pick up the fix automatically when it gets made upstream.

**Closed by arfon** 2016-06-01 16:30 UTC
